### ISSUE TITLE
fvtk.label won't show up if called twice 

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#1]
_From @samuelstjean on April 24, 2014 15:3_

Try this : 

> > > from dipy.viz import fvtk
> > > r=fvtk.ren()
> > > l=fvtk.label(r)
> > > fvtk.add(r,l)
> > > fvtk.show(r)

You get origin in white, show it again, and you only get a black scene (on my computer). 
fvtk.show(r) # nothing happens :( 

I'm on ubuntu 12.04, could be a vtk problem or a rendering problem, points show up fine for example and don't exibit this behavior.

_Copied from original issue: nipy/dipy#353_

**Comment by dmreagan** [comment]
`fvtk` is not a part of FURY and I couldn't replicate this bug with the newer `window.Scene` and `actor.label`.
