### ISSUE TITLE
Replace md5 by sha2 or sha3 for security issue

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#121]
Following [this link](https://docs.python.org/2/library/md5.html), `md5` is insecure and deprecated. 

We should update `dipy.data.fetcher.py`, specially [here](https://github.com/fury-gl/fury/blob/master/fury/data/fetcher.py#L75-L107)  and [here](https://github.com/fury-gl/fury/blob/master/fury/data/fetcher.py#L248) for our data.

**Comment by arokem** [comment]
I don't think that we need to worry too much about the security issues, since we're using the hashes for data validation, not for encryption. But the long-term support is definitely a concern, and reason enough to move.

**Comment by skoudoro** [comment]
Agree, Thank for the feedback.  it was just a reminder 😄.

**Comment by lenixlobo** [comment]
Hello,
I have updated fetcher.py to support sha256 in place of md5.
Could anyone provide the input SHA hash code to test the updated source?

**Comment by skoudoro** [comment]
The input SHA code is the content of the file. We read the file as a string and generate the code from that

**Comment by lenixlobo** [comment]
On line 251 in fetcher.py a stored MD5 hash is provided
The function _get_file_md5() computes a hash which is compared in check_md5()  with the stored hash on line 102.

**Comment by skoudoro** [comment]
fixed by #148.closing
