### ISSUE TITLE
Documentation not being rendered correctly

### ISSUE THREAD

**Issue by jhlegarreta** [fury-gl/fury#122]
## Description
The documentation of some methods is not being rendered correctly: the variable name and the type are rendered with no space in between: compare for example the documentation of
[fury.actor.line](https://fury.gl/latest/reference/fury.actor.html#line)
[fury.actor.scalar_bar](https://fury.gl/latest/reference/fury.actor.html#scalar-bar)
[fury.actor.streamtube](https://fury.gl/latest/reference/fury.actor.html#streamtube)
[fury.actor.label](https://fury.gl/latest/reference/fury.actor.html#label)
to
[fury.io.load_image](https://fury.gl/latest/reference/fury.io.html#load-image)
or
[fury.actor.set_input](https://fury.gl/latest/reference/fury.actor.html#fury.actor.set_input)
or
[fury.window.analyze_snapshot](https://fury.gl/latest/reference/fury.window.html#fury.window.analyze_snapshot)

The issues are not limited to the above examples: virtually documentation of all files show the same issue.

It looks like the white space preceding the colon is the pattern that distinguishes an incorrect documentation rendering from a correct one. However, the `NumPy` style documentation [does show](https://numpydoc.readthedocs.io/en/latest/format.html#sections) such a white space.

`NumPy`'s source code does show such a white space as well, so may be the issue is in `Sphinx` or the system used to generate the documentation (?).

## Way to reproduce
Check the online documentation (links above) or generate the documentation the way it is currently generated and check it locally.

**Comment by jhlegarreta** [comment]
@skoudoro @Garyfallidis Any insight as to why this is happening?

**Comment by skoudoro** [comment]
Thank you for reporting that @jhlegarreta. 

I do not know the reason yet. It seems it was already the case with the previous fury doc version so need to look a bit deeper to NumpyDoc and Sphinx.

**Comment by jhlegarreta** [comment]
May be we are missing the [`numpydoc`](https://pypi.org/project/numpydoc/) or [`Napoleon`](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) extensions to [correctly parse the docstrings](https://docs.python-guide.org/writing/documentation/#writing-docstrings) (look for "sphinx.ext.napoleon" in the latter)? 

Napoleon is a [built-in extension](https://www.sphinx-doc.org/en/master/usage/extensions/index.html).
