### ISSUE TITLE
window.record() resolution limit

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#13]
_From @dmreagan on February 9, 2018 18:43_

## Description
`window.record()` can be used to save a render to a PNG image. If you set the `size` to be higher than your monitor size, the resulting image will be capped to just under your monitor's resolution. For example, if you set `size=(5000, 5000)`, but your monitor's resolution is (1920, 1080), the image width will end up being something like 1916 pixels. 

## Way to reproduce
Run any viz example that saves a render with `window.record()`, but change the `size` to be very high. Tested on Windows and Mac with VTK 7.

_Copied from original issue: nipy/dipy#1420_

**Comment by skoudoro** [comment]
_From @ShreyasFadnavis on March 12, 2018 21:31_

Can you review my pull request for this? #1453

**Comment by skoudoro** [comment]
_From @dmreagan on March 13, 2018 2:31_

@ShreyasFadnavis  and @karandeepSJ report that they had no trouble with large resolutions on their systems.  Can you both report which OS, Python, and VTK versions you are using to get these successful results?

**Comment by skoudoro** [comment]
_From @ShreyasFadnavis on March 13, 2018 2:37_

@dmreagan I tested this on both Windows 10 and Ubuntu 16.04. 
Python Version: 3.6.4
VTK Version: 7.1.1

**Comment by skoudoro** [comment]
_From @karandeepSJ on March 13, 2018 10:26_

Ubuntu 16.04
Python Version: 3.5.2
VTK Version: 8.1.0

**Comment by skoudoro** [comment]
Hi @dmreagan,

a potential fix, look at the last answer: http://vtk.1045678.n5.nabble.com/Offscreen-rendering-beyond-screen-resolution-with-WindowToImageFilter-magnification-td5724102.html

**Comment by skoudoro** [comment]
_From @thechargedneutron on May 4, 2018 21:58_

@dmreagan  Is this issue on Ubuntu as well? Upon changing the size to (6000, 6000) I got a file with a size of (6000, 6000).

**Comment by skoudoro** [comment]
_From @thechargedneutron on May 4, 2018 22:24_

@skoudoro  very nicely figured the problem. @dmreagan  I have added a patch in my branch [here](https://github.com/thechargedneutron/dipy/tree/window_resolution). Can you please verify if this is working fine since this issue is not there on Ubuntu I guess.

**Comment by scott-trinkle** [comment]
what's the status on this? I'm running into this problem as well.

**Comment by skoudoro** [comment]
It is fixed on #53, I need to revise and I was waiting for a review. 

It will be good if you can review it @scott-trinkle :smile:

**Comment by scott-trinkle** [comment]
just tested it using the code from your branch. I'm on OSX and it's working if I use the `magnification` keyword to bump the resolution over the screen limit, but not if I try to set the output resolution directly.
