### ISSUE TITLE
Backward compatibilities problem with streamtube

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#135]
## Description

After playing with `dipy_horizon`, you can see that streamlines are in Black&White instead of color when you use the master branch instead of the release 0.4.0.
 
The recent PR (#129) change the original behavior so :

- we have to get back to the original behavior
- find a workaround to manage the new color features  (look at the old one [here](https://github.com/fury-gl/fury/blob/maint/v0.4.0/fury/actor.py#L445))

**Comment by Nibba2018** [comment]
@skoudoro I don't think I understand the issue properly. Are the streamlines black & white even though the default parameter is RGB?

**Comment by skoudoro** [comment]
I am working on this issue, no worries ;-) thank you

**Comment by Nibba2018** [comment]
@skoudoro  Great :+1:
