### ISSUE TITLE
Issues with provided spheres

### ISSUE THREAD

**Issue by nasimanousheh** [fury-gl/fury#137]
Hello,

Using ``primitive.prim_sphere(name='repulsion724', gen_faces=False)`` does not provide correct information to then calculate normals. Although symmetric724 does.
Furthermore, ``gen_faces=True`` shifts the sphere away from its center.
Similarly, most provided spheres have the same problem.

Thank you!

**Comment by agent87** [comment]
> Hello,
> 
> Using `primitive.prim_sphere(name='repulsion724', gen_faces=False)` does not provide correct information to then calculate normals. Although symmetric724 does.
> Furthermore, `gen_faces=True` shifts the sphere away from its center.
> Similarly, most provided spheres have the same problem.
> 
> Thank you!
@nasimanousheh do you have the code to the error?
