### ISSUE TITLE
Box, cone etc. to work similarly to superquadric

### ISSUE THREAD

**Issue by Garyfallidis** [fury-gl/fury#138]
Currently the superquadric function uses repeat_primitive_function. The rest of the actors need to change too so they are easier to use.
For example box has a single scale and heights parameter which does not allow to make boxes of different sizes with one call. We should be able to have boxes of different sizes with one call.

**Comment by Saransh0905** [comment]
@Garyfallidis 
We can make cubes of different sizes by specifying cube height and centers array like:
`from fury import window, actor`
`scene = window.Scene()`
`centers = np.array([[1,1,1],[1.8,1.8,1.8],[2.3,2.3,2.3]])`
`dirs = np.array([1,1,1])`
`heights = np.array([1,1.2,1.4])`
`cube_actor = actor.cube(centers, dirs, (1, 1, 1), heights=heights)`
`scene.add(cube_actor)`
`window.show(scene)`
Or is it something else you are talking about?
Thanks
