### ISSUE TITLE
There are libraries we have to install not mentioned in the requirement.txt file to run the test case.

### ISSUE THREAD

**Issue by Pabla007** [fury-gl/fury#155]
## Description
[Please provide a general introduction to the issue/proposal.]
pip install nose
pip install pytest

[If reporting a bug, attach the entire traceback from Python and follow the way to reproduce below]
Otherwise you many get into the following error so please add this in the requirement.txt
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]
![1](https://user-images.githubusercontent.com/35897183/75094530-f965eb80-55b1-11ea-8039-8a54b2604ecc.PNG)
![2](https://user-images.githubusercontent.com/35897183/75094532-f9fe8200-55b1-11ea-805f-e6440729cca3.PNG)

## Way to reproduce
[If reporting a bug, please include the following important information:]
After installing the fury in the development mode than while run this code
- [From python interpreter:
$ from fury.tests import test
$ test() ] Code example
- [ ] Relevant images (if any)
- [![3](https://user-images.githubusercontent.com/35897183/75094553-2dd9a780-55b2-11ea-8e48-59a8f80c7b26.PNG) ] Operating system and versions (run `python -c "from fury import get_info; print(get_info()"`)

**Comment by skoudoro** [comment]
Hi @Pabla007,

Thank you for this information. Requirements file for dev are in this folder: https://github.com/fury-gl/fury/tree/master/requirements

I agree with you that we need to add this information to the website. Feel free to create a Pull Request with this information.
