### ISSUE TITLE
Saved Images are vertically Inverted

### ISSUE THREAD

**Issue by Nibba2018** [fury-gl/fury#160]
## Description
Images saved by fury.window.record() are inverted vertically.

### Code example:
```python
from fury import window, actor
scene = window.Scene()
a = actor.axes()
scene.add(a)
window.record(scene)
``` 
### Relevant Image:
![Inverted Image](https://ibin.co/5DLHfDW86mgi.png)

### OS Info and Version
{'fury_version': '0.4.0.post133+g13809a1',
'pkg_path': '/home/nibba/GSoC/fury/fury',
'commit_hash': '13809a10cb4a6753f166ef547ac6a087357189ad',
'sys_version': '3.7.6 (default, Jan 8 2020, 19:59:22) \n[GCC 7.3.0]',
'sys_executable': '/home/nibba/miniconda3/envs/fury-gl/bin/python',
'sys_platform': 'linux',
'numpy_version': '1.18.1',
'scipy_version': '1.4.1',
'vtk_version': '8.2.0',
'matplotlib_version': '3.1.3',
'dipy_version': '1.1.0'}

**Comment by Nibba2018** [comment]
@skoudoro can you hint me where I should be hunting for this bug?

**Comment by skoudoro** [comment]
The bug appears on `window.record(scene)` so we should inspect this

**Comment by Pabla007** [comment]
@skoudoro I have gone through the code i think there is problem in the **arr** after reshaping it.
So i have gone through the **save_image** code and made some changed  in the pillow  code and got the image as aspected. But i am failing the test case.

![result1](https://user-images.githubusercontent.com/35897183/75571235-cb374e80-5a7e-11ea-9448-71995cfd9fac.PNG)
![failing](https://user-images.githubusercontent.com/35897183/75571249-cf636c00-5a7e-11ea-83f9-f1ed557675d3.PNG)

I will gone  in deep and see is after **reshaping** we are getting the output right. But some help might be appreciate here.
