### ISSUE TITLE
window.show() is giving Attribute error.

### ISSUE THREAD

**Issue by Pabla007** [fury-gl/fury#172]
Description
window.show( ) when i was running the **viz_slice.ipynb** example i was testing different options like window.record() and window.snapshot() they are working fine. But when i use window.show() and click on the image it produces this error. 

Way to reproduce
Code example
window.show(scene, title='FURY', size=(300, 300), png_magnify=1,
            reset_camera=True, order_transparent=False, stereo='off',
            multi_samples=8, max_peels=4, occlusion_ratio=0.0)
Relevant images (if any)
![error 124](https://user-images.githubusercontent.com/35897183/75608172-39355180-5b23-11ea-9f1d-c11ad30d3133.PNG)

Operating system and versions
{'fury_version': '0.4.0.post198+g10c977e', 'pkg_path': '/home/jasims/fury/fury', 'commit_hash': '10c977e343aa23141dda26fce5dd08257197216d', 'sys_version': '3.7.4 (default, Aug 13 2019, 20:35:49) \n[GCC 7.3.0]', 'sys_executable': '/home/jasims/miniconda3/bin/python', 'sys_platform': 'linux', 'numpy_version': '1.18.1', 'scipy_version': '1.4.1', 'vtk_version': '8.1.2', 'matplotlib_version': '3.1.3', 'dipy_version': '1.1.1'}

**Comment by skoudoro** [comment]
Duplicate nfrom #160, closing
