### ISSUE TITLE
Allowing to change text position on Sliders

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#176]
Currently, the text position is by default:

- below the slider on the horizontal slider.
- on the left of the slider for a vertical slider.

it will be good to offer the possibility to be
- on the top of the slider for the horizontal slider
- on the right of the slider for the vertical slider

**Comment by PaulNicolasHunter** [comment]
I have raised a PR for this issue, where I've addressed a slight change for the horizontal slider.
I think for the vertical slider, #165 is not merged yet.

Let me know if you wan't any other workaround,

**Comment by skoudoro** [comment]
Thank you @PaulNicolasHunter for looking into it. I will look at your PR

**Comment by PaulNicolasHunter** [comment]
@skoudoro I've made another PR #189, I've made text adding more dynamic and added tutorials and tests, however, I can't find why it is failing at Travis.
Any guesses?
