### ISSUE TITLE
Utility functions are needed for getting numpy arrays from actors

### ISSUE THREAD

**Issue by Garyfallidis** [fury-gl/fury#179]
We need utility functions for the following functions that we are using a lot.
```
actor.GetMapper().GetInput().GetPoints().GetData())
actor.GetMapper().GetInput().GetPoints().GetData().Modified()
actor.GetMapper().GetInput().ComputeBounds()
```
The functions should move to utils. or transform. 
I suggest names such as vertices_from_actor, modify_actor and compute_bounds.
We should have something similar for faces too. faces_from_actor.

**Comment by Gs-001** [comment]
I would like to work on this issue. I'll read through and code and documentation and get back to you if there's any doubt.
Do the discussions generally take place here or on the IRC ?

**Comment by ibrahimAnis** [comment]
Hiiii @skoudoro I have made some changes as you suggested. Can you see my PR #187 and give me feedback so that I can improve

**Comment by skoudoro** [comment]
Hi @ibrahimAnis, you did not address all my suggested comments. Can you fix them? Thank you

**Comment by ibrahimAnis** [comment]
> Hi @ibrahimAnis, you did not address all my suggested comments. Can you fix them? Thank you

I have done it. I don't think I made a good testcase for update_actor() and compute_bounds(). Could you check it and give me feedback . Please!

**Comment by ibrahimAnis** [comment]
Hiiii @Garyfallidis  I have been working on creating test file for compute_bounds() function adn update_actor() function and I have found that the ComputeBounds() function is not defined in any header file. Instead GetBounds() function is defined and it is also widely used in fury. So can I make a function that returns the bounds of actor. The implementation would be something like this
actor.GetMapper().GetInput().GetBounds()

**Comment by ibrahimAnis** [comment]
Please reply soon. @skoudoro  I would like to have your feedback about it.
Thanks

**Comment by skoudoro** [comment]
Hi @ibrahimAnis,

> So can I make a function that returns the bounds of actor. The implementation would be something like this

`actor.GetMapper().GetInput().GetBounds()` is not needed yet so do not implement it.

> I have found that the ComputeBounds() function is not defined in any header file

What do you mean? Did you look at this link: https://vtk.org/doc/nightly/html/classvtkDataSet.html#a261a4f32cd2f8ff336c2d85cc33d21ae

Your PR is on my TODO list. This PR looks simple but needs some time to check it in detail. This is why I did not do it yet. I will try tomorrow or on Monday.

**Comment by ibrahimAnis** [comment]
![computeBounds](https://user-images.githubusercontent.com/31585047/77243371-55fb0b80-6c2f-11ea-8580-ada88af1dcfe.png)

You can see only this much is written in header file

**Comment by ibrahimAnis** [comment]
Is there any lib file where all the definitions are defined ?

**Comment by skoudoro** [comment]
You can find what you need on vtk gitlab.

But I am trying to understand what is your goal?

**Comment by ibrahimAnis** [comment]
can you please share the link

**Comment by ibrahimAnis** [comment]
Actually I want to know how ComputeBounds function works so that I can make test file for it

**Comment by ibrahimAnis** [comment]
Can you please share the link where I can see the definition of functions defined in vtkPoint.h header file

**Comment by ibrahimAnis** [comment]
I got it. Thanks for your help
