### ISSUE TITLE
Dipy visualization (fvtk) crash when saving series of images

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#2]
_From @mick-d on May 12, 2015 22:29_

I wrote a script to save a series of slice visualization (ellipsoids) with dipy vtk module (`fvtk`). However after a few slices (around 6) python crashes with only error message "Segmentation fault (core dumped)".

The script goes:

```
tenmodel = dti.TensorModel(my_gradient_table)
tenfit = tenmodel.fit(my_masked_dwi_data)
RGB = color_fa(my_FA_image, tenfit.evecs)
sphere = get_sphere('symmetric724')
ren = fvtk.ren()
for iSlice in range(0,tenfit.evals.shape[2]):
    fvtk.add(ren, fvtk.tensor(tenfit.evals[:,:,iSlice:iSlice+1], tenfit.evecs[:,:,iSlice:iSlice+1], RGB_scaled[:,:,iSlice:iSlice+1], sphere))
    fvtk.record(ren, n_frames=1, out_path='slice_'+("%03d" % iSlice)+'.png', size=(1000, 1000)) 
    fvtk.clear(ren) 
```

_Copied from original issue: nipy/dipy#645_

**Comment by dmreagan** [comment]
`fvtk` is not a part of FURY and I couldn't replicate this bug using the newer `actor.tensor_slicer`, `window.record`, and `window.Scene`.
