### ISSUE TITLE
Window Title name does not change

### ISSUE THREAD

**Issue by namanb009** [fury-gl/fury#202]
window.show(scene, titile="Window Name") does not change the name of the window.
Also, the default name of the window should be "FURY", but when a window is called, its name is "Visualisation Toolkit".

**Comment by skoudoro** [comment]
Hi @namanb009,

good catch for the windows title. I think, this problem only appears on Windows and macOS. It should work well on Linux, I need to check.

**Comment by namanb009** [comment]
Thank you @skoudoro 

I am using the following config:
Windows 10
Python 3.5
VTK 8.1.2
