### ISSUE TITLE
Create a tutorial for checkbox/radiobutton UI

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#205]
Currently, there is no existing Tutorial for `CheckBox`and `RadioButton` UI. We need to create a small one to show this feature as we did for the sliders.

**Comment by PaulNicolasHunter** [comment]
cool, I'll have a look.

**Comment by Nibba2018** [comment]
@PaulNicolasHunter  are you working on this?

**Comment by PaulNicolasHunter** [comment]
@Nibba2018 hi, actually I had some tasks rolled up, so, I was thinking to start working on this before the weekend hits, probably on Friday.

**Comment by Nibba2018** [comment]
@PaulNicolasHunter Okay cool :+1:

**Comment by PaulNicolasHunter** [comment]
@skoudoro, I've added a tutorial for RadioButton UI, I've played around with the colors of the cube with it.
Let me know if it's cool or you want me to implement some other idea for the ease of the tutorials.

**Comment by skoudoro** [comment]
ok, I will look into it and let you know on the PR. But it sounds promising!

**Comment by vivekvj18** [comment]
Can I Do This Task...#205?
@skoudoro

**Comment by skoudoro** [comment]
Hi @vivekvj18,

Thank you for asking, there is already someone working on that as you can see on #208.
I will try to add more beginner-friendly issue this week. So check regularly [**good first issue tag**](https://github.com/fury-gl/fury/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)

**Comment by skoudoro** [comment]
Fixed by #281. Closing
