### ISSUE TITLE
Peak slicer doesn't honor linewidth parameter

### ISSUE THREAD

**Issue by dmreagan** [fury-gl/fury#22]
Changing the `linewidth` doesn't change the width of the peak lines. You can change the width manually with 

```python
actor.GetProperty().SetLineWidth(5)
```

**Comment by jhlegarreta** [comment]
In fact, it also happened for the `opacity` as well.

Now, I ignore whether the same happens for the `TensorSlicerActor` or other similar actors as well. In the specific case of the `TensorSlicerActor` although the `opacity` is being passed as an argument, it is not actually being used.

**Comment by dmreagan** [comment]
You're right about the tensor slicer. We should be setting the opacity on the actor's property, as in `line`. This may be a problem for other actors, too, but I haven't yet looked. Feel free to add a tensor slicer fix to #43, or we can make another issue + PR for it.

**Comment by jhlegarreta** [comment]
I'd go for another, separate PR.
