### ISSUE TITLE
DOC: sphinx_gallery master branch is required

### ISSUE THREAD

**Issue by MarcCote** [fury-gl/fury#23]
At the moment, the master branch of sphinx_gallery is needed in order to build the docs (`sphinx_gallery.scrapers` will be missing otherwise). That means installing the `requirements/docs.txt` won't work as it will install sphinx_gallery v0.2.0.

**Comment by skoudoro** [comment]
Indeed, I think we need to change this part. Maybe we can temporarily add the current sphinx-gallery master on `docs/source/ext`.

Furthermore, we need to find a way to run sphinx-gallery with xvfbwrapper. Currently, we can not test if the tutorials and examples are running correctly on Travis. This is a serious limitation for deploying the docs with Travis.
