### ISSUE TITLE
PR idea: create SDF alternatives to FURY primitive actors

### ISSUE THREAD

**Issue by dmreagan** [fury-gl/fury#247]
Create SDF versions of common shapes like sphere, cone, cylinder, arrow, and superquadric.

Architecture question: how should these be implemented?

* single SDF actor: `sdf(type='arrow')`
* many separate new actors: `arrow_sdf`, `cone_sdf`, ...
* SDF options within the existing actors: `arrow(sdf=true)`

**Comment by skoudoro** [comment]
I vote for :
-single SDF actor: `sdf(type='arrow')`

**Comment by lenixlobo** [comment]
1. Should I proceed with adding the SDF actors in actor.py ? or create a few sdf.py script?
2. Should I apply the shader to the box_actor primitive?

**Comment by skoudoro** [comment]
> Should I proceed with adding the SDF actors in actor.py ? or create a new sdf.py script?

yes,  in `actor.py`. do not create a new file 

> Should I apply the shader to the box_actor primitive?

yes @lenixlobo
