### ISSUE TITLE
Programs with timers hang on exit. [VTK9] [Linux]

### ISSUE THREAD

**Issue by MarcCote** [fury-gl/fury#253]
## Description
With VTK9 on Ubuntu 18.04 programs that use timers (sometimes) hang on exit. Also, if it doesn't hang, I get this error message:
```
fury/tests/test_ui.py::test_timer X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  25 (X_SendEvent)
  Resource id in failed request:  0x200002
  Serial number of failed request:  156
  Current serial number in output stream:  163
```

I was able to track the issue to https://github.com/fury-gl/fury/blob/master/fury/window.py#L661 where timers get destroy on exit. That line was introduced in https://github.com/fury-gl/fury/pull/97 by @Garyfallidis. I'm not sure why timers get destroyed manually? I think we should let VTK handle that but we should clear the Python list `self.timers` for good measure.

That said, I don't know why with VTK9 those programs hang but not with prior versions of VTK. I'll open an issue on the VTK's GitLab once I manage to reproduce the problem with a C++ example.

## Way to reproduce
`pytest -svv fury/tests/test_ui.py::test_timer`

**Comment by skoudoro** [comment]
VTK released 9.0.1 and there is wheel for Linux, Windows and Mac. 

Can you check if you still have the problem @MarcCote?  I think we can close this issue.

**Comment by MarcCote** [comment]
So, VTK 9.0.1 indeed solved the `TimerEvent` issue but not the error message I get when manually deleting the timers.
```
platform linux -- Python 3.8.3, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- /home/macote/miniconda3/envs/vtk9/bin/python
cachedir: .pytest_cache
rootdir: /data/src/fury
collected 1 item                                                                                                                                                                                                                             

fury/tests/test_ui.py::test_timer X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  25 (X_SendEvent)
  Resource id in failed request:  0x6000002
  Serial number of failed request:  119
  Current serial number in output stream:  126
```

**Comment by Nibba2018** [comment]
Hello @MarcCote , I tried running some programs on both Windows and Linux and found that the `VTK warnings` that are generated are shown in a different window in windows, whereas the same window doesn't show up in Linux. The following error is shown at the end of such a program. Maybe if we can fix it by preventing the Warning Window from generating in the first place.
