### ISSUE TITLE
Changes to shader API in VTK 9

### ISSUE THREAD

**Issue by dmreagan** [fury-gl/fury#260]
When running FURY shader code with VTK 9, I now see warnings like this:

```
vtkOpenGLPolyDataMapper:227   WARN| 
vtkOpenGLPolyDataMapper::AddShaderReplacement was deprecated for VTK 9.0 and will be removed in a future version.  
Use vtkOpenGLShaderProperty::AddShaderReplacement instead.
```

The new implementation comes from [this commit](https://github.com/Kitware/VTK/commit/1b005a294d34f5628dc029fa943047cff9629f22), where the new classes and some examples of their use can be found.

We probably don't need to do anything until:

- FURY moves to a requirement of `vtk>=9.0.0` or
- VTK removes the feature instead of just deprecating it

**Comment by skoudoro** [comment]
Indeed, we need a shader API to manage all of them. Thank you for pointing that
