### ISSUE TITLE
Some issues with actor.box after release 0.6.0

### ISSUE THREAD

**Issue by nasimanousheh** [fury-gl/fury#271]
Hello,

- In actor.py, the parameter "scale" in box should be "scales" (lines 1600 and 1611);
- The colors should be at the range of [255, 0, 255]. Otherwise it does not work.

Thank you all for the great work pushing this forward!

**Comment by nasimanousheh** [comment]
Also RGBA  is not working in colors parameter of the box. RGB works.

**Comment by skoudoro** [comment]
Thank you for the feedback @nasimanousheh. 

This issue is related to #242. `Bo`x is not the only actor with this issue. We need to normalize this point in FURY.

concerning RGBA, I supposed all primitives have this issue. We need to look deeper into it. Seems related to #269
