### ISSUE TITLE
Update Demos/tutorial

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#297]
## Description

Demos / Tutorials needs reshaping:

- [x] from @Garyfallidis :  Physics demo should move to demos
- [x] from @nasimanousheh : In viz_wrecking_ball.py, when I change the  radii (line 37) from 0.1 to 1, the collision happens before the ball reaches the bricks.
- [ ] from @pjsjongsung: Does the two UI tutorials have to be separate? It has some overlapping examples.Also, if they are separate, I think you should add fetch_viz_icons in Basic UI Elements tutorial also, because the tutorials assume you already have the icons data

Each recommendation should be addressed in a separate PR

**Comment by pjsjongsung** [comment]
also in the fury installation document, to run the tests, it tells you to be in the FURY package dir, where as the location(in windows, I haven't checked with other OS) should actually be site-packages dir(which is the one before fury). minor, but worth fixing?

**Comment by tushar5526** [comment]
@skoudoro  for the third task, what exactly have to be done ? Do I have to move the advanced UI to UI ?

**Comment by skoudoro** [comment]
yes, 
- the folder `advanced_ui` should be deleted.
- the tutorial `viz_ui.py` should move to `02_ui`
- the Readme in `02_UI` should be updated. I think, just removing the word `basic` everywhere is enough.
