### ISSUE TITLE
Wrecking Ball Simulation

### ISSUE THREAD

**Issue by nasimanousheh** [fury-gl/fury#298]
In "Wrecking Ball Simulation" (viz_wrecking_ball.py), the simulation does not respond correctly as I change the value of radii (line 37). 

I think it can be fixed if:

- The value of "radii" (line 37) should be the same as the value of "ball_radius" (line 40);
- In line 204, it should be "radii=ball_radius" instead of "radii=0.2": 

ball_actor = actor.sphere(centers=np.array([[0, 0, 0]]),
                          radii=0.2,
                          colors=np.array([1, 0, 1]))

**Comment by skoudoro** [comment]
Thank you for reporting @nasimanousheh. Can you look at it @Nibba2018 ? Thank you

**Comment by Nibba2018** [comment]
Hello @nasimanousheh , the `radii` parameter at line 37 is for the radius of the rope segments i.e the cylinders. The rope is built using multiple cylinder segments (No. of segments = `n_links`). The `ball_radius` parameter should be used to change the radius of the ball.

Yes, you are correct about line 204, I forgot to update the `0.2` with `ball_radius` variable. Line 120 should also be updated.

**Comment by nasimanousheh** [comment]
Thank you @Nibba2018!
Do you know why when I change the "radii" to be 0.5, or even more (while ball_radius = 0.2), the bricks collapse before the ball touches them? But when I define both  "radii"  and "ball_radius" with same value (for example 0.5), it works well. I think there must be a connection between them.

**Comment by Nibba2018** [comment]
@nasimanousheh , I think the rope segments hit the wall before the ball does. You can replace `p.connect(p.DIRECT)` on line 20 with `p.connect(p.GUI)` to view the pybullet version of the simulation. Currently, due to #293 , the rope is not rendered properly in fury and thats why it appears as if the wall collapses before the ball collides.

**Comment by nasimanousheh** [comment]
I understand now. Thank you @Nibba2018!

**Comment by Garyfallidis** [comment]
@Nibba2018 is there an issue in place for the cylinder?

**Comment by Nibba2018** [comment]
Yes @Garyfallidis , I have created #293 for the cylinder issue.
