### ISSUE TITLE
Dipy visualization with missing (?) affine parameter

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#3]
_From @mick-d on May 12, 2015 22:30_

I would like to add slices and other elements in dipy `fvtk` visualization but no `affine` parameter is available for element such as `dipy.viz.fvtk.slicer`.  The `voxsz` parameter helps rescaling but what about rotation/translation/etc.?

_Copied from original issue: nipy/dipy#646_

**Comment by dmreagan** [comment]
Besides being a question for the now-deprecated `fvtk`, I think this problem is covered by #10.
