### ISSUE TITLE
Clipping overflowing text from the left.

### ISSUE THREAD

**Issue by Nibba2018** [fury-gl/fury#308]
The current implementation of `clip_overflow` in `fury.ui` allows us to clip overflowing text from the right end for a given width. It will be helpful to have a feature that can clip overflowing text from the left end as well. The overflowing text must be replaced by `...`. This feature will be helpful while developing `FileDialog2D`.

For e.g 
if `extraordinary` overflows for a given width then it must be replaced by `...ordinary` where `...ordinary` is the perfect fit for that width.

**Comment by tushar5526** [comment]
Issues with **hacktoberfest** tags has to be solved in october only ? :p

**Comment by Nibba2018** [comment]
Yes @tushar5526 , If you create PRs before October then they wont be eligible for Hacktoberfest.

**Comment by rishigarg94** [comment]
can I work on this issue pls?

**Comment by Nibba2018** [comment]
Hey @rishigarg94 , @tushar5526 claimed it first so if he plans to work on some other issue then I will assign this to you.

Also @tushar5526 , aren't you planning to work on #313 ?

**Comment by rishigarg94** [comment]
> 
> 
> Hey @rishigarg94 , @tushar5526 claimed it first so if he plans to work on some other issue then I will assign this to you.
> 
> Also @tushar5526 , aren't you planning to work on #313 ?

sure

**Comment by tushar5526** [comment]
Yes @Nibba2018, I am done with #313 will submit a PR soon.

**Comment by rishigarg94** [comment]
can you pls explain with some example... it is not clear what you wnat to do,

like, do you want "extraordinary" to be display as "...ordinary" ?
in case of width limit reach?
 or something else?

**Comment by Nibba2018** [comment]
Great @tushar5526 , then I am assigning this issue to @rishigarg94 .

Yes exactly @rishigarg94 . The entire string `...ordinary` should be a perfect fit for the given width.

**Comment by rishigarg94** [comment]
> 
> 
> Great @tushar5526 , then I am assigning this issue to @rishigarg94 .
> 
> Yes exactly @rishigarg94 . The entire string `...ordinary` should be a perfect fit for the given width.

yes thanks for assigning me...
means, you don't wnat "extraordinary" to be shown as "extr..." you want it to be "...ary"? like this?

**Comment by Nibba2018** [comment]
> yes thanks for assigning me...
> means, you don't wnat "extraordinary" to be shown as "extr..." you want it to be "...ary"? like this?

Yes @rishigarg94

**Comment by rishigarg94** [comment]
> 
> 
> > yes thanks for assigning me...
> > means, you don't wnat "extraordinary" to be shown as "extr..." you want it to be "...ary"? like this?
> 
> Yes @rishigarg94

ok sure

**Comment by Nibba2018** [comment]
@rishigarg94 Updates?

**Comment by tushar5526** [comment]
@Nibba2018 Can I do it ?

**Comment by Nibba2018** [comment]
@tushar5526 sure, go ahead
