### ISSUE TITLE
Domino Physics Simulation

### ISSUE THREAD

**Issue by Nibba2018** [fury-gl/fury#309]
Add a Physics Simulation demo to showcase the following Domino effect:
![domino](https://i.imgur.com/aYhJRSX.gif)

To know more about Physics simulations refer to this [document](https://docs.google.com/document/d/1XJcG1TL5ZRJZDyi8V76leYZt_maxGp0kOB7OZIxKsTA/edit?usp=sharing).

**Comment by SanjayMarreddi** [comment]
Hey @Nibba2018 ,

I would like to work on this issue. Could you please assign this to me and brief it out as well ! 

Thanks and Regards,
Sanjay Marreddi.

**Comment by Nibba2018** [comment]
Hello @SanjayMarreddi , this issue is reserved for Hacktoberfest so if you are interested kindly reclaim it after 1st October.

**Comment by SanjayMarreddi** [comment]
@Nibba2018 
Yeah I am Interested in Hacktoberfest. I will reclaim after 1st October.
Thanks for your Information.

**Comment by SanjayMarreddi** [comment]
Hey @Nibba2018 
Could you please assign this to me now !

**Comment by Nibba2018** [comment]
@SanjayMarreddi Sure! go Ahead

**Comment by Nibba2018** [comment]
@SanjayMarreddi Any updates?

**Comment by SanjayMarreddi** [comment]
@Nibba2018  I was too busy with Academic Exams and Other Events till Tomorrow..
I have done implementing this about 60-70%. I just need to make sure that Bricks follow the Pattern. I will try to complete this before the end of this October Month. 
Hope you Understand !
Thanks !!

**Comment by Nibba2018** [comment]
@SanjayMarreddi Okay no problem :+1:
