### ISSUE TITLE
Rendering bug in SDF actor when not all primitives are defined

### ISSUE THREAD

**Issue by dmreagan** [fury-gl/fury#310]
## Description
If you don't define a primitive for each of your SDFs, it will render bit turds on the surface of the box for that SDF. FURY should do some combination of the following:

- be more clear about the primitive behavior in the documentation
- warn the user if they don't provide enough primitives
- assume a default for missing primitives

![fury_sdf_primitive_bug](https://user-images.githubusercontent.com/6951528/93240322-fc911680-f751-11ea-8002-968f2cbc2bca.gif)

## Way to reproduce
Start with the _viz_sdfactor.py_ tutorial. This tutorial creates 3 SDFs. But if you only define one or two primitives, you'll see the bug. 

```
sdfactor = actor.sdf(centers=centers, directions=dirs, colors=colors,
                     primitives=['sphere', 'torus'],
                     scales=scales)
```

Note that you can set one primitive for all SDFs by using a single string instead of an array. But if you use an array with just a single string, you get the bug.

This behavior has been observed on Linux with VTK 9.0.1.

**Comment by tushar5526** [comment]
We can set the missing primitive to the default value i.e. `torus` or set it to the primitive at index 0. Another option could be to throw an error. What should I prefer?
