### ISSUE TITLE
Adding Physics Integration Docs to FURY's Website

### ISSUE THREAD

**Issue by Nibba2018** [fury-gl/fury#312]
- fury-pybullet integration [doc](https://docs.google.com/document/d/1XJcG1TL5ZRJZDyi8V76leYZt_maxGp0kOB7OZIxKsTA/edit?usp=sharing) needs to be added to FURY's [Website](https://fury.gl/).
- `rst` syntax should be respected
- the document should be in `fury/doc/source`

**Comment by jhlegarreta** [comment]
Maybe [pandoc](https://pandoc.org/) can come in handy to have a first/working draft.

**Comment by iadi7ya** [comment]
Hey @Nibba2018 I would like to work on this issue. Can you please assign this to me.

**Comment by Nibba2018** [comment]
Hello @iadi7ya , this issue is reserved for Hacktoberfest so kindly reclaim it after 1st Oct.

**Comment by iadi7ya** [comment]
> Hello @iadi7ya , this issue is reserved for Hacktoberfest so kindly reclaim it after 1st Oct.

Definitely. Thanks!

**Comment by devsapariya94** [comment]
i have a doubt that which framework is used in the website??

**Comment by skoudoro** [comment]
The framework used is Sphinx. @devsapariya94. This is quite common in python world. Please, check doc folder to see how to build the docs. It will help you.

**Comment by AmalChandru** [comment]
Hai, Is this still open?

**Comment by Nibba2018** [comment]
Hey @AmalChandru , a PR already been made to solve this issue. Kindly look for other issues to solve.
