### ISSUE TITLE
Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#315]
An update is needed on [`github_tools.py`](https://github.com/fury-gl/fury/blob/master/docs/source/ext/github_tools.py) script.

We need to use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

More information [here](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param)

**Comment by tushar5526** [comment]
Can I do it ?
