### ISSUE TITLE
Cylinder primitive generation

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#318]
It would be good to have a function that generates the vertices and triangles of a cylinder. 

Primitives examples are available [here](https://github.com/fury-gl/fury/blob/master/fury/primitive.py).

**Comment by tushar5526** [comment]
@skoudoro I would like to do it. Can you brief a little, like do you want the vertices and triangles of capped and uncapped cylinders too?

**Comment by skoudoro** [comment]
Great! Thanks @tushar5526. 

If we could have both, it would be perfect! Just add a boolean option/parameter `capped`.

**Comment by tushar5526** [comment]
Great! I will be referring to [this](https://github.com/p5py/p5/blob/master/p5/core/primitives3d.py#L319) code from p5py ( processing for python )

**Comment by skoudoro** [comment]
We try to avoid adding a dependency when it is not necessary so you can reimplement it and refer to this code on the docstring but do not import this package, please 😄 (even if it is a good one though)

**Comment by skoudoro** [comment]
Furthermore, the GPL License from p5py is problematic for us.

So you should avoid copy code or import the package. You will need to reimplement it @tushar5526

**Comment by tushar5526** [comment]
@skoudoro Yes, I will be not importing the package, by referencing I meant the algorithm to generate the vertices & triangles (if that's not an issue ).
Thank you for pointing out the GPL license, I will keep that in mind :)
