### ISSUE TITLE
Unable to set up the project locally for python 32bit system

### ISSUE THREAD

**Issue by NEERAJAP2001** [fury-gl/fury#333]
## Description

Hello, I wanted to set up the project locally in my pc , I cloned te project but when running this command 
```pip install -r requirements/default.txt```   

 It shows this error 
``` 
ERROR: Could not find a version that satisfies the requirement vtk!=9.0.0,>=8.1.2 (from -r requirements/default.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for vtk!=9.0.0,>=8.1.2 (from -r requirements/default.txt (line 3))
```

System details : 
Windows 10 
python version ```Python 3.8.5``` (32bit)

## Way to reproduce

- [x] Code example
- [ ] Relevant images (if any)
- [x] Operating system and versions (run `python -c "from fury import get_info; print(get_info())"`)
```   
import vtk
ModuleNotFoundError: No module named 'vtk'
```

**Comment by NEERAJAP2001** [comment]
I tried 
``` 
pip install vtk
```
It shows this 
```
ERROR: Could not find a version that satisfies the requirement vtk (from versions: none)
ERROR: No matching distribution found for vtk
```

**Comment by Nibba2018** [comment]
@NEERAJAP2001 VTK only provides 64-bit wheels for [PyPI](https://pypi.org/project/vtk/#files). Try installing python 64-bit and try again. You can choose to use [miniconda](https://docs.conda.io/en/latest/miniconda.html) which provides 64-bit python by default.

**Comment by skoudoro** [comment]
I confirm VTK supports only a 64bit system. So we do the same. I recommend you to install a compatible python version. I am closing this issue.
