### ISSUE TITLE
From travis (pricing model changed) to github Actions ? 

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#338]
The pricing model of Travis changed. Our macOS matrix stopped to work if we do not pay. here more informations: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing.

We need to read this carefully all the changes and we need to remove/replace our macOS matrix

> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:

> Your account name and VCS provider How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount)

Also, this is not good sign

**Comment by arokem** [comment]
I'm definitely a 👍 for GHA. I've had a pleasant experience with the projects I have there. Let me know if you want help setting this up. I can point you to some examples and help debug issues.

**Comment by skoudoro** [comment]
Do you any experience with Xvfb and GHA @arokem?

It seems I have some issue with that. Can you have a look at my PR #342. 
Furthermore, I tried to keep the backward compatibility with Travis but I am not sure it is a good idea.

Thank you in advance for your feedback
