### ISSUE TITLE
Some Typos & Grammatical Errors to be fixed in WIKI GSOC 2021

### ISSUE THREAD

**Issue by iamansoni** [fury-gl/fury#354]
Some typos and grammatical errors need to be fixed for a better understanding of the wiki GSOC 2021 Documentation.

Link: https://github.com/fury-gl/fury/wiki/Google-Summer-of-Code-2021

**Comment by skoudoro** [comment]
Hi, 

Thanks for letting us know. We can not make the wiki for EDIT so feel free to details all the typo and grammatical errors in a comment here. you can create a simple table with before and after correction. 

We will update after that.

**Comment by Ayushsunny** [comment]
I wanna work on this issue.

**Comment by Nibba2018** [comment]
Hi @skoudoro , wouldn't it be a good idea to add one of our physics simulation gifs under Project 6?
