### ISSUE TITLE
unwanted objects rendering randomly

### ISSUE THREAD

**Issue by shubhamr2511** [fury-gl/fury#359]
## Description
2 randomly coloured cylinders rendering along with monkey. Cylinder are not supposed to be rendered.

## Way to reproduce
create new scene in blender 2.90
delete everything in scene
add new monkey mesh
shade smooth
export as .obj (suzanne.obj) in working directory
run the python code copied from [getting started page](https://fury.gl/latest/getting_started.html))

## Environment
OS : Ubuntu 20.04
FURY 0.6.1
Python 3.8.5

![code](https://user-images.githubusercontent.com/76848874/104497892-042dd280-5601-11eb-9a4e-0fd9c45f3792.png)
![output1](https://user-images.githubusercontent.com/76848874/104497932-127bee80-5601-11eb-9b09-6e581b1614f2.png)
![output2](https://user-images.githubusercontent.com/76848874/104498043-363f3480-5601-11eb-9b8f-e4aac90ba445.png)
![output3](https://user-images.githubusercontent.com/76848874/104498080-3e976f80-5601-11eb-9cf2-14bb476bc048.png)
For each execution Output is different. 3 of them are attached.
![blender Scene](https://user-images.githubusercontent.com/76848874/104498232-70a8d180-5601-11eb-8648-5a78fbe8c1a5.png)

**Comment by tushar5526** [comment]
@shubhamr2511  you are adding those cylinders in the code. They are being positioned randomly. Check the following lines in your code
```
cylinders = actor.cylinder(....)
scene.add(cylinders)
scene.add(suzzane)
```

**Comment by skoudoro** [comment]
+1 with @tushar5526 answer, so I am closing this issue
