### ISSUE TITLE
Minor error in documentation of create_colormap function

### ISSUE THREAD

**Issue by SunTzunami** [fury-gl/fury#363]
## Description

This is with respect to the [create_colormap function.](https://fury.gl/latest/_modules/fury/colormap.html#create_colormap)

According to the comment describing the `auto` variable, if `auto` is True then v is interpolated to **[0, 10]** from v.min() to v.max(). In the actual code however, v is being interpolated to **[0, 1]** from v.min() to vmax(). I think that this can be fixed by either editing the comment to specify that v is interpolated from [0, 1] or by altering the code to interpolate v from [0, 10].

**Comment by ganimtron-10** [comment]
I edited the Docs and Changed the docs according to your suggestion as I thought this way would be the Best and created a pull request...
[My Pull Request](https://github.com/fury-gl/fury/pull/368)

**Comment by skoudoro** [comment]
Thank you @SunTzunami, fixed by #368, closing
