### ISSUE TITLE
Card2D UI widget

### ISSUE THREAD

**Issue by antrikshmisri** [fury-gl/fury#397]
**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to a problem. It is merely an addition of a widget to fury's UI modules

**Describe the solution you'd like**
The `Card2D` should be divided into three sections `Image`, `Title`, `Body`. The image will be scaled in accordance with a scaling factor (between 0 , 1) for example a scaling factor of 0.5 will result in the image covering half the space of the card. The rest of the space will be divided into title and body. Both the title and body should be `TextBlock2D` and the image should be an `ImageContainer2D`.

**Describe alternatives you've considered**
I couldn't find any alternative widget in fury's UI module.

**Additional context**
Here is a screenshot for reference:-
![Screenshot (176)](https://user-images.githubusercontent.com/54466356/112531915-2fd1f380-8dce-11eb-8372-8aa6a0ef7510.png)

**Comment by antrikshmisri** [comment]
@skoudoro I would like to work on this widget

**Comment by ganimtron-10** [comment]
Added with #398
