### ISSUE TITLE
fvtk contour function ignores voxsz parameter

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#4]
_From @mick-d on May 12, 2015 22:34_

When trying to display an ROI, fvtk render the slice in the same place, even when provided with a different voxsz parameter.
In my case the following two commands provided the same results:

```
cc_ROI_actor = fvtk.contour(my_ROI_data, levels=[1], colors=[(1., 1., 0.)], opacities=[1.], voxsz=(2.5, 2.5, 2.5)) 
r = fvtk.ren()
fvtk.add(r, cc_ROI_actor)
fvtk.show(r)
```

```
cc_ROI_actor = fvtk.contour(my_ROI_data, levels=[1], colors=[(1., 1., 0.)], opacities=[1.]) 
fvtk.clear(r)
fvtk.add(r, cc_ROI_actor)
fvtk.show(r)
```

_Copied from original issue: nipy/dipy#647_

**Comment by dmreagan** [comment]
`fvtk` is not a part of FURY and the newer `actor.contour_from_roi` doesn't have a `voxsz` parameter.
