### ISSUE TITLE
Sphere actor does not appear when vertices and faces are used

### ISSUE THREAD

**Issue by nasimanousheh** [fury-gl/fury#400]
## Description
When I use 'theta' and 'phi' parameters in sphere actor, I can see the spheres in the window. But I don't see any spheres when I use 'vertices' and 'faces' parameters. 

Here is the code sample to verify the issue:
```
from fury import actor, primitive, window
import fury
print(fury.__version__)
print(fury.__file__)
import numpy as np

scene = window.Scene()
sphere_res = 'symmetric362'
vertices, faces = primitive.prim_sphere(name=sphere_res,
                                        gen_faces=False)
pos = 10 * np.random.rand(100, 3)
colors = 100 * np.ones((100, 3), dtype='uint8')
radii_spheres = 2+np.random.rand(100)
sphere_actor = actor.sphere(centers=pos,
                                colors=colors,
                                radii=radii_spheres,
                                vertices=vertices,
                                faces=faces)
scene.add(sphere_actor)
window.show(scene)
```
Thank you all!

**Comment by skoudoro** [comment]
Hi @nasimanousheh,

Thank you for pointing that out.

I see several potential mistakes:
- colors is between [0-1].  I don't think you need to multiply by 1000
- vertices, faces, have only 1 sphere (and you want 100 spheres), they are not duplicating after. So you have to do it yourself. 
- why do you `prim_sphere`? I do not see the goal here

I need to tests your example but it will be good if you could check these 2 points first.

**Comment by skoudoro** [comment]
ok, we will look into this issue.

a temporary solution for you is:
```python
from fury import actor, primitive, window, utils
import fury
import numpy as np

scene = window.Scene()
vertices, faces = primitive.prim_sphere(name='symmetric362',
                                        gen_faces=False)
pos = np.array([[0,0,0]])
res = primitive.repeat_primitive(vertices, faces, centers=pos)
big_verts, big_faces, big_colors, _ = res
sphere_actor = utils.get_actor_from_primitive(big_verts, big_faces, big_colors)
scene.add(sphere_actor)
window.show(scene)
```

**Comment by SunTzunami** [comment]
I tried debugging it, there are perhaps three functions that can contain clues - primitive.prim_sphere, actor.sphere (which in turn uses utils.repeat_sources). I think primitive.prim_sphere works fine as I tried it and it returned the correct vertices and faces for the 'symmetric362' sphere. This leaves [actor.sphere](https://github.com/fury-gl/fury/blob/d921fb0177183ce5d4267a36c09f76033204d7f6/fury/actor.py#L1313) and [utils.repeat_sources](https://github.com/fury-gl/fury/blob/d921fb0177183ce5d4267a36c09f76033204d7f6/fury/utils.py#L578).
When I don't typecast the vertices on [this line](https://github.com/fury-gl/fury/blob/d921fb0177183ce5d4267a36c09f76033204d7f6/fury/utils.py#L610), it seems to work as can be seen in this preview- 
![image](https://user-images.githubusercontent.com/65067354/113573082-0c614100-9637-11eb-8bf4-be16850472c8.png)
PTAL @nasimanousheh , @skoudoro.


> Thank you for the corrections.
> I fixed the code, but still the problem is not solved.
> **why do you prim_sphere?** Currently, I'm using sphere actor in my application. There are 906 vertices in each sphere and it takes time to visualize more than1000 spheres. I want to use prim_sphere with less vertices (362 vertices or even 100 vertices).
> 
> ```
> from fury import actor, primitive, window
> import fury
> import numpy as np
> 
> scene = window.Scene()
> vertices, faces = primitive.prim_sphere(name='symmetric362',
>                                         gen_faces=False)
> pos = np.array([[0,0,0]])
> sphere_actor = actor.sphere(centers=pos,
>                             colors=1,
>                             radii=0.5,
>                             vertices=vertices,
>                             faces=faces)
> scene.add(sphere_actor)
> window.show(scene)
> ```
