### ISSUE TITLE
ImageContainer2D renders RGB .png images in black and white

### ISSUE THREAD

**Issue by antrikshmisri** [fury-gl/fury#402]
## Description
The ImageContainer2D UI component renders any RGB image with .png extension in black and white.

## Way to reproduce

1.  Imort ImageContainer2D from `fury.ui`
```python
from fury.ui import ImageContainer2D
```
2. Make a ImageContainer2D object
```python
img = ui.ImageContainer2D(img_path="path_to_png_image",
                          position=(250, 250) , size=(500, 500))
```
3. Add the component to the scene
```python
current_size = (1000, 1000)
show_manager = window.ShowManager(size=current_size,
                                  title="Image")

show_manager.scene.add(img)
show_manager.start()
```
## System Information:
```
{'fury_version': '0.7.0.post21+g0b160ec', 'pkg_path': 'D:\\pythonProjects\\fury\\fury', 'commit_hash': '0b160ecef6767054a6d8f5cafdf3e636925f917f', 'sys_version': '3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]', 'sys_executable': 'D:\\pythonProjects\\fury\\venv\\Scripts\\python.exe', 'sys_platform': 'win32', 'numpy_version': '1.19.5', 'scipy_version': '1.5.4', 'vtk_version': '9.0.1', 'dipy_version': '1.4.0'}
```
## Screenshots:
![Screenshot (177)](https://user-images.githubusercontent.com/54466356/112946317-00671200-9153-11eb-8b97-8f6688778e0c.png)

## Conjecture:
I think the function in question is [load_image](https://github.com/fury-gl/fury/blob/58d45a4c64514924247226e6390b3c05b3703ce7/fury/io.py#L9). More specifically when the image is being rendered as a vtk type

**Comment by jhalak27** [comment]
Hey, I reproduced the output with this code:
```
from fury import window, ui
img = ui.ImageContainer2D(img_path="dice.png",
                          position=(250, 250) , size=(500, 500))
                      
current_size = (1000, 1000)
show_manager = window.ShowManager(size=current_size,
                                  title="Image")

show_manager.scene.add(img)
show_manager.start()
```
I got the image in RGB. Couldn't find the issue you are referring to. 

The output was: 
![Screenshot from 2021-04-04 17-37-37](https://user-images.githubusercontent.com/41876178/113508262-a0b2a180-956c-11eb-8483-6057dface81f.png)

**Comment by antrikshmisri** [comment]
@jhalak27 Hmm, this weird I have tried this with many images and I get the same result i.e. a black and white image. Can you try it out with more examples?  I am using [this](https://raw.githubusercontent.com/fury-gl/fury-communication-assets/main/fury-logo.png) image.

**Comment by jhalak27** [comment]
Tried this too.
Got this result.
![Screenshot from 2021-04-07 17-58-42](https://user-images.githubusercontent.com/41876178/113866578-1e73e880-97cb-11eb-93cf-66bfa6b4bff7.png)
