### ISSUE TITLE
Creating test for layout module

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#403]
Tests are missing for the layout module (`layout.py`). This issue is just a reminder to create some tests for this module. 

-> `fury/layout.py` (pytest -svv `fury/test_layout.py`)

**Comment by AmPhIbIaN26** [comment]
Hey I was looking to solve this issue, if I may can you tell me a bit more about it??

**Comment by skoudoro** [comment]
Hi @AmPhIbIaN26,

Please, check how we run unit test in FURY, and then you can follow the same pattern as the other unit test.

**Comment by jhalak27** [comment]
Hey, Can I take this up?

**Comment by skoudoro** [comment]
Yes, go ahead @jhalak27

**Comment by jhalak27** [comment]
I created PR #411. Can you have a look?
