### ISSUE TITLE
module 'fury.window' has no attribute 'Scene'

### ISSUE THREAD

**Issue by vinkirk** [fury-gl/fury#41]
## Description
Hi,

I am going through the tutorial examples for Fury (version 0.1.4) and while running the code for the example 'Using a timer', I got the following error message:

import fury
import numpy as np
from fury import window, actor, ui
import itertools

xyz = 10 * np.random.rand(100, 3)
colors = np.random.rand(100, 4)
radii = np.random.rand(100) + 0.5

scene = window.Scene()
Traceback (most recent call last):

  File "<ipython-input-1-de7b112ab010>", line 10, in <module>
    scene = window.Scene()

AttributeError: module 'fury.window' has no attribute 'Scene'

Thanks for your help,

Vinny

**Comment by skoudoro** [comment]
Hi @vinkirk, 

Sorry for that, This is the dev version of the documentation and not the release version of the documentation.
you can go to http://fury.gl/v0.1.x/auto_tutorials/viz_timers.html for the release v0.1.4 version.
I will update this link asap. 

Thank you for this info!

**Comment by skoudoro** [comment]
TODO
-------
- [ ] add dropmenu for selecting documentation version (latest vs releases vs dev)

**Comment by vinkirk** [comment]
Thanks @skoudoro!
