### ISSUE TITLE
ListBox2D has resizing issues when added into TabUI

### ISSUE THREAD

**Issue by ganimtron-10** [fury-gl/fury#418]
## Description
When we add `ListBox2D` in the `TabUI` its creates a unnecessary scrollbar bigger than itself and `ListItems` too have big backgrounds, which on clicking resizes properly.

### My Code
```python
from fury import ui,window

sm = window.ShowManager(title='Resize Tuts',size=(1366,738))
# Individual ListBox
l = ui.ListBox2D(values=['Red1','Blue1','Green1'])
sm.scene.add(l)

# ListBox added to TabUI
l1 = ui.ListBox2D(values=['Red1','Blue1','Green1'])
l2 = ui.ListBox2D(values=['Violet','Indigo','Blue','Yellow','Green','Orange','Red'],position=(10,10))

t = ui.TabUI(size=(500,500),nb_tabs=3,draggable=True,position=(100,100))
t.add_element(0,l1,(0.1,0.1))
t.add_element(1,l2,(10,10))

sm.scene.add(t)

sm.start()
```

### ScreenShots
![Issue-Img1](https://user-images.githubusercontent.com/64432063/115110679-36512680-9f9a-11eb-98e5-74006e496fab.png)
![Issue-Img2](https://user-images.githubusercontent.com/64432063/115110693-49fc8d00-9f9a-11eb-891e-88a7867bb18e.png)

## System Info
`
{'fury_version': '0.7.0.post45+g31efc5a', 'pkg_path': '/home/ganimtron10/Desktop/VSCode/Fury-Workspace/fury/fury', 'commit_hash': '31efc5a8a4b18dab43093723d3259b30881ab6aa', 'sys_version': '3.8.5 (default, Jan 27 2021, 15:41:15) \n[GCC 9.3.0]', 'sys_executable': '/home/ganimtron10/Desktop/VSCode/Fury-Workspace/fury-env/bin/python', 'sys_platform': 'linux', 'numpy_version': '1.20.2', 'scipy_version': '1.6.2', 'vtk_version': '9.0.1'}
`

**Comment by Nibba2018** [comment]
Hi @ganimtron-10 , is someone working on this issue right now?

**Comment by ganimtron-10** [comment]
No @Nibba2018 , Currently no one is working on this.
Feel free to go ahead.

**Comment by Nibba2018** [comment]
Okay :+1:
