### ISSUE TITLE
Colormap not working as intended with surface actor

### ISSUE THREAD

**Issue by SunTzunami** [fury-gl/fury#429]
## Description
 Colormap is not being mapped to the actor when generating a surface using surface actor. Colormap helps in visualizing elevation. 

## Code example 

```
import numpy as np
from fury import window, actor, colormap

## grid
x = np.linspace(-1, 1, 100)
y = np.linspace(-1, 1, 100)
X, Y = np.meshgrid(x, y)
X = X.reshape(-1)
Y = Y.reshape(-1)

## elevation
Z = 0.48*np.sin(2*np.pi*(X))*np.cos(2*np.pi*(Y))
xyz = np.vstack([X, Y, Z]).T

## colormap
v = np.copy(Z)
v /= np.max(np.abs(v),axis=0)
colors = colormap.create_colormap(v, name='spring')

surface_actor = actor.surface(xyz, colors=colors)

scene = window.Scene()
scene.background((1, 1, 1))
scene.zoom(10.5)
scene.set_camera(position=(-32, 50, 60), focal_point=(0.0, 0.0, 0.0), view_up=(0.34, -0.630, 0.68))
scene.add(surface_actor)
window.show(scene, size=(400, 400))
```
## Preview of the output 

![elevation](https://user-images.githubusercontent.com/65067354/116779575-aaa8c100-aa94-11eb-92a1-415d23c18ff6.png)

As can be seen in the output, the actor returned by the surface actor doesn't have the correct color.

**Comment by amitchaudhari9121** [comment]
This should be fixed once the above PR gets merged. 

For future readers:
---
The method expected a 0-255  ranged values for color input.

but the `colors = colormap.create_colormap(v, name='spring')` would generate a 0-1 ranged values.
this resulted in the actor not displaying the color map properly.
Fix was to change the actor definition a bit.
