### ISSUE TITLE
Deprecation warning raised in from `utils.numpy_to_vtk_cells`

### ISSUE THREAD

**Issue by arokem** [fury-gl/fury#431]
While reviewing https://github.com/dipy/dipy/pull/2375, I got the following deprecation warning: 

```
Users/arokem/miniconda3/envs/dipy/lib/python3.8/site-packages/fury/utils.py:97: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  data = np.array(data)
```

**Comment by arokem** [comment]
Sorry: more details. This happens when I run the `bundle_assignment_maps.py` example in the aforementioned PR.

**Comment by skoudoro** [comment]
We need to check but I think it has been already fixed on master.

Thank you for the feedback @arokem.

**Comment by skoudoro** [comment]
I confirm this is fixed. Closing
