### ISSUE TITLE
Issue with references related to JOSS review

### ISSUE THREAD

**Issue by danielskatz** [fury-gl/fury#450]
This is from @phamvanvung - copied from https://github.com/openjournals/joss-reviews/issues/3445

For the review of this software in https://github.com/openjournals/joss-reviews/issues/3384,  @phamvanvung has an issue regarding the references. He wrote

> References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper citation syntax?

I hope he can describe the issue in more detail.

**Comment by skoudoro** [comment]
Thank you for letting us know! We will update the references on the website and the paper.

**Comment by Garyfallidis** [comment]
Updates were addressed in #453, #454 and #455 which are currently merged.

**Comment by danielskatz** [comment]
👋 @phamvanvung - I'm going to close this, but feel free to repoen it or add another issue if you feel there's still a problem
