### ISSUE TITLE
Improve loading speed using partial imports

### ISSUE THREAD

**Issue by Garyfallidis** [fury-gl/fury#457]
We can try to make our scripts load faster by importing only the functions we need from VTK. This is supposed to be supported from VTK 9 and on. Let's try it.

The issue was reported during our JOSS review https://github.com/openjournals/joss-reviews/issues/3384 by N.P. Rougier.

**Comment by skoudoro** [comment]
This issue has been addressed by all the PR's above. We can close it for now. We still need to compare the performance. This can be done on a new issue.
