### ISSUE TITLE
`GridUI` throws error when captions are `None`

### ISSUE THREAD

**Issue by antrikshmisri** [fury-gl/fury#463]
## Description
When the `captions` parameter is set to `None` the `GridUI` throws the following error:-
```python
'vtkmodules.vtkRenderingOpenGL2.vtkOpenGLActor' object has no attribute '_items'
  File "fury/ui/containers.py", line 774, in init
    self._actors.append(item._items[0])
  File "grid_testing.py", line 15, in <module>
    grid = ui.GridUI(actors)
```
This is being caused because with captions the actors are converted to a `Container` that has the actor and the text but when captions are set to None the actor is passed as is, thus throwing `AttributeError`.

## Way to reproduce
1. Run the following code (captions set to None), to see the error.
```python
from fury import window, actor, ui
import numpy as np


scene = window.Scene()
scene.zoom(12.5)
scene.set_camera(position=(60, 40, 30), focal_point=(0.0, 0.0, 0.0),
                 view_up=(0.0, 0.0, 1.0))
showm = window.ShowManager(scene, size=(600, 600))

sp1 = actor.sphere(np.zeros((1, 3)), colors=np.random.rand(3), radii=1)
sp2 = actor.sphere(np.zeros((1, 3)), colors=np.random.rand(3), radii=1)

actors = [sp1, sp2]
sgrid = ui.GridUI(actors)  # gives an error\
```
A patch needs to be made somewhere over [here](https://github.com/antrikshmisri/fury/blob/d498b6d1cf7b9594f55a80cfcbc047a9c8fd5bd1/fury/ui/containers.py#L773-L775).

**Comment by skoudoro** [comment]
Good catch! thank you for pointing that

**Comment by aadityasinha-dotcom** [comment]
Is this issue available?

**Comment by ganimtron-10** [comment]
Hello @aadityasinha-dotcom ,
I have worked on this issue and created a PR regarding the same!!
Feel free to look around for another issues.
Thanks!

**Comment by aadityasinha-dotcom** [comment]
Okay

**Comment by skoudoro** [comment]
fixed by https://github.com/fury-gl/fury/pull/478. closing
