### ISSUE TITLE
Mismatch in parameter and docstring in manifest_standard() in material module

### ISSUE THREAD

**Issue by SunTzunami** [fury-gl/fury#469]
Parameter `interpolation` is set to string [here](https://github.com/fury-gl/fury/blob/master/fury/material.py#L34) but in the [docstring](https://github.com/fury-gl/fury/blob/master/fury/material.py#L52-L54), it says that it's a float.

**Comment by SunTzunami** [comment]
Also, should we have option of more types of interpolations other than Phong too? Other types of interpolation supported by vtk can be found [here](https://vtk.org/doc/nightly/html/classvtkProperty.html#a5c95702d226c4f4783957b7f3a98c069).

**Comment by SunTzunami** [comment]
Another thing, parameter `specular_power` is set to 10 [here](https://github.com/fury-gl/fury/blob/master/fury/material.py#L33) but the according to the [docstring](https://github.com/fury-gl/fury/blob/master/fury/material.py#L51) it's supposed to be between 0 and 1.

**Comment by skoudoro** [comment]
Thank you for the feedback @SunTzunami!

Can you address this @guaje in a quick PR?

**Comment by guaje** [comment]
@SunTzunami thanks for catching this. I'm already working on the corrections on the documentation.

Regarding other types of interpolation, that is also a work in progress, and those features will come in other PRs.

**Comment by skoudoro** [comment]
Fixed by #488, closing
