### ISSUE TITLE
Adding a utility function to convert a numpy array to vtkImageData

### ISSUE THREAD

**Issue by antrikshmisri** [fury-gl/fury#500]
**Is your feature request related to a problem? Please describe.**

Currently, FURY has no utility method to convert a numpy array to vtkImageData. This will be useful in directly loading numpy arrays in `ui.ImageContainer2D` instead of `imageDataGeometryFilter`

**Describe the solution you'd like**

A utility function named `numpy_to_vtk_image_data` or something similar needs to be added in `fury/utils`.

**Comment by skoudoro** [comment]
Thank you for this issue. We also need to update #491 after having this function

**Comment by skoudoro** [comment]
fixed by #509, closing
