### ISSUE TITLE
Text justification in vtkTextActor3D

### ISSUE THREAD

**Issue by xtanion** [fury-gl/fury#526]
## Description
Text justification of vtkTextActor3D seems to be working fine. There's a  `_update_user_matrix()` method in the text3d in fury, with or without this method, the text actor's justifications are working in the same way.  

-------------------------------------------------------------------------------------

Using fury text3D:
```py
text3d_1 = actor.text_3d("Left Top")
text3d_1.vertical_justification('top')
text3d_1.justification('left')
text3d_2 = actor.text_3d("Right Bottom")
text3d_2.vertical_justification('bottom')
text3d_2.justification('right')
```
Output:
![image](https://user-images.githubusercontent.com/74976752/150080865-b946bd70-6b2b-49bc-8622-e16a4fd08be3.png)

--------------------------------------------------------------------------------

Using vtkTextActor3D:
```py
vtkText_1 = vtkTextActor3D()
vtkText_1.SetInput('LeftTop')
vtkText_1.GetTextProperty().SetVerticalJustificationToTop()
vtkText_1.GetTextProperty().SetJustificationToLeft()
vtkText_2 = vtkTextActor3D()
vtkText_2.SetInput('RightBottom')
vtkText_2.GetTextProperty().SetVerticalJustificationToBottom()
vtkText_2.GetTextProperty().SetJustificationToRight()
```
Output:
![image](https://user-images.githubusercontent.com/74976752/150081293-4cdb373e-de23-43af-a248-71dd1aff0b9a.png)

**Comment by skoudoro** [comment]
Hi @xtanion,

Thank you for reporting. Are you sure that the goal of `_update_user_matrix` is to do the justification? I did not check yet. However, there is a clear difference between your 2 screenshots. One is blurry. I will look deeper at `_update_user_matrix` but not sure this is an issue.

**Comment by xtanion** [comment]
In  `_update_user_matrix` there was a comment that says "Text justification of vtkTextActor3D doesn't seem to be working, so we do it manually." 
In the 2nd example, I forgot to set font size and scale it, After that the blurriness goes away. here's the preview
```py
    vtkText_1 = vtkTextActor3D()
    vtkText_1.SetInput('LeftTop')
    vtkText_1.GetTextProperty().SetFontSize(24)
    vtkText_1.SetScale((1./24.*12,)*3)
    vtkText_1.GetTextProperty().SetVerticalJustificationToTop()
    vtkText_1.GetTextProperty().SetJustificationToLeft()

    vtkText_2 = vtkTextActor3D()
    vtkText_2.SetInput('RightBottom')
    vtkText_2.GetTextProperty().SetFontSize(24)
    vtkText_2.SetScale((1./24.*12,)*3)
    vtkText_2.GetTextProperty().SetVerticalJustificationToBottom()
    vtkText_2.GetTextProperty().SetJustificationToRight()
```
![image](https://user-images.githubusercontent.com/74976752/150157691-d641f48e-6d2c-49c1-9608-7e4459734ff3.png)
