### ISSUE TITLE
Arrow actor needs to use repeat_primitives by default

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#530]
This will allow the arrow to have the same behavior when picking vertices or edges as with other primitives.

However, we should also keep repeat_sources as a secondary option just in case we need to use some of the other VTK filters.

See an example of box actor (using repeat_primitives) here https://github.com/fury-gl/fury/blob/master/fury/actor.py#L1696

See the current implementation of arrow here https://github.com/fury-gl/fury/blob/master/fury/actor.py#L1768

**Comment by soma2000-lang** [comment]
@skoudoro  I am working on this

**Comment by Aditi840** [comment]
hello, I saw this issue open can I on this.

**Comment by skoudoro** [comment]
fixed by @m-agour on #552. closing
