### ISSUE TITLE
Current PBR version has issue with Spherical Harmonics 

### ISSUE THREAD

**Issue by nasimanousheh** [fury-gl/fury#539]
## Description
Thank you for all the outstanding work with this upcoming release. Everything does work great apart from this issue.

With current master I am getting Scene has no attribute UseSphericalHarmonicsOff

```
File "c:\Users\nasim\Devel\fury\docs\examples\viz_pbr_interactive.py", line 127, in <module>
    scene = window.Scene(skybox=cubemap)
  File "c:\users\nasim\devel\fury\fury\window.py", line 42, in __init__
    self.UseSphericalHarmonicsOff()
AttributeError: 'Scene' object has no attribute 'UseSphericalHarmonicsOff'
```

## Way to reproduce
Simply run the ``viz_pbr_interactive.py`` tutorial in docs/examples

I believe this issue needs to be fixed before the release. Also shouldn't this example be in docs/tutorials/03_shaders?

Finally, the other PBR tutorial has no issue. The one that does not use a skybox. I mean the one called ``viz_pbr_spheres.py``.

**Comment by skoudoro** [comment]
Hi @nasimanousheh ,

Please, update your VTK version. This function is only available on VTK 9.1.0.   FURY will depend only on VTK 9.1.0.

Any older version will generate this error.
