### ISSUE TITLE
generating directed arrows

### ISSUE THREAD

**Issue by PDN96** [fury-gl/fury#54]
Hello,
I have been trying to generate directed arrows using fury's arrow function but it doesn't seem to work. I ended up writing a function on my own for the same. 
I think it would a good addition to fury.

![directed_arrow](https://user-images.githubusercontent.com/13295296/52906652-52bc7180-321e-11e9-9a79-8a4fa442d1c8.PNG)

**Comment by skoudoro** [comment]
Can you create a PR with the good one and show the bad version? Thank you

**Comment by skoudoro** [comment]
Fixed, closing
