### ISSUE TITLE
Allow offscreen rendering in window.record.

### ISSUE THREAD

**Issue by Garyfallidis** [fury-gl/fury#541]
The record function creates empty and black windows that can be problematic during testing or when running our tutorials.
A solution to this could be by setting offscreen equals 1 (as used in snapshot).
```
render_window = RenderWindow()
    if offscreen:
        render_window.SetOffScreenRendering(1)
```

We should also test if we can call record iteratively without any issues after this modification.

**Comment by skoudoro** [comment]
solved by #564, closing
