### ISSUE TITLE
Double requirement given for Pillow in default.txt

### ISSUE THREAD

**Issue by Nibba2018** [fury-gl/fury#585]
## Description
Hello, installing requirements via pip leads to the following error:
```
ERROR: Double requirement given: Pillow>=8.0.1 (from -r requirements/default.txt (line 7)) (already in pillow>=5.4.1 (from -r requirements/default.txt (line 5)), name='Pillow')
```

## Way to reproduce
- [X] Code example
`pip install -r requirements/default.txt`
- [X] Operating system and versions (run `python -c "from fury import get_info; print(get_info())"`)

```
{'fury_version': '0.4.0.post2215+gadd8cc0e', 'pkg_path': '/home/nibba/OSS/fury/fury', 'commit_hash': 'add8cc0e3b1f75008da4c7cd168fd5b8d8888da0', 'sys_version': '3.7.9 (default, Aug 31 2020, 12:42:55) \n[GCC 7.3.0]', 'sys_executable': '/home/nibba/miniconda3/envs/fury-gl/bin/python', 'sys_platform': 'linux', 'numpy_version': '1.19.4', 'scipy_version': '1.5.4', 'vtk_version': '9.0.1', 'matplotlib_version': '3.3.3', 'dipy_version': '1.3.0'}
```

**Comment by xtanion** [comment]
Hi @Nibba2018, I installed fury on a venv using `requirements/default.txt.` It installed Pillow version>=8.0.1. I tried installing `pillow < 8.0.1`, and it worked fine. Can you confirm which version of `pillow` it installs on your system by default?
(p.s. all tests are working fine on both pillow<8.0.1 and Pillow>=8.0.1)

**Comment by Nibba2018** [comment]
Hello @xtanion , I was trying to update my dependencies on my exiting environment when I faced this issue. Apparently when I try to install them on a fresh environment it works fine. Anyways, thank you for your response. I will close this issue then.
(I was using `conda` and my existing `Pillow` version was: 8.0.1)
