### ISSUE TITLE
UI tests are failing in Ubuntu OS due to a "segmentation error"

### ISSUE THREAD

**Issue by m-agour** [fury-gl/fury#603]
## Description
UI tests are failing because of a "segmentation error" in Ubuntu only.
@xtanion confirmed it on his machine.
The error message is:
`tests/test_elements_callback.py Fatal Python error: Segmentation fault`
I tried to trace back the cause of this error and it's not caused by the test in which this error occurred.
Running only `test_elements_callback.py` gives a success.

## Way to reproduce
Running the UI tests in Ubuntu OS.

**Comment by skoudoro** [comment]
Thank you @m-agour.

`Segmentation errors` are always hard to track and find the cause but we will look into it.

**Comment by filipinascimento** [comment]
Maybe related to https://github.com/fury-gl/fury/issues/578 ?

**Comment by m-agour** [comment]
> Maybe related to #578 ?
> 
> Can you try the code that I provide there as a pytest and see if you also get an error?
> 
> To further investigate this we need a minimal example. I suspect it is a bug in vtk.



> Maybe related to #578 ?
> 
> Can you try the code that I provide there as a pytest and see if you also get an error?
> 
> To further investigate this we need a minimal example. I suspect it is a bug in vtk.



> Maybe related to #578 ?
> 
> Can you try the code that I provide there as a pytest and see if you also get an error?
> 
> To further investigate this we need a minimal example. I suspect it is a bug in vtk.

@filipinascimento, I will try it and let you know

**Comment by m-agour** [comment]
@filipinascimento @skoudoro I tried getting to a minimal way to produce the error but I couldn't. I also tried mulithreading  and it sometimes produces this error depending on the number of threads.
A quick way to avoid this error is to run the `test_elements_callback` first before the other tests. A way to do it is changing its name to for example `test_1_elements_callback`.

**Comment by m-agour** [comment]
I managed to narrowed it down. So the following test would produce the `segmentation fault`.
```
import os
from fury import window, ui
from fury.data import DATA_DIR

def test_1():
    scene = window.Scene()
    show_manager = window.ShowManager(scene)
    show_manager.initialize()
    show_manager.start()
    filename = "test_ui_file_menu_2d"
    recording_filename = os.path.join(DATA_DIR, filename + ".log.gz")

    show_manager = window.ShowManager(size=(600, 600), title="FURY FileMenu")
    show_manager.play_events_from_file(recording_filename)
    filemenu = ui.FileMenu2D(size=(500, 500),
                             directory_path=os.getcwd())
    show_manager = window.ShowManager(size=(600, 600),
                                      title="FURY FileMenu")
    show_manager.scene.add(filemenu)
    show_manager.start()
```
If `show_manager.play_events_from_file(recording_filename)` is deleted, the error does not occur, so I suspect it's the one causing the error but not sure why.
This test is not only causing the problem I believe. since I didn't eliminate the other tests.

**Comment by skoudoro** [comment]
Thank you @Nibba2018

**Comment by m-agour** [comment]
> I managed to narrowed it down. So the following test would produce the `segmentation fault`.
> 
> ```
> import os
> from fury import window, ui
> from fury.data import DATA_DIR
> 
> def test_1():
>     scene = window.Scene()
>     show_manager = window.ShowManager(scene)
>     show_manager.initialize()
>     show_manager.start()
>     filename = "test_ui_file_menu_2d"
>     recording_filename = os.path.join(DATA_DIR, filename + ".log.gz")
> 
>     show_manager = window.ShowManager(size=(600, 600), title="FURY FileMenu")
>     show_manager.play_events_from_file(recording_filename)
>     filemenu = ui.FileMenu2D(size=(500, 500),
>                              directory_path=os.getcwd())
>     show_manager = window.ShowManager(size=(600, 600),
>                                       title="FURY FileMenu")
>     show_manager.scene.add(filemenu)
>     show_manager.start()
> ```
> 
> If `show_manager.play_events_from_file(recording_filename)` is deleted, the error does not occur, so I suspect it's the one causing the error but not sure why.

Hello @Nibba2018,
There is also this test case where it gives a segmentation fault running it separately. It does not give an error running it as a normal code though.
It's not an actual test but rather a fabricated one. so no need to fix it. But it might give you an insight into what's causing this error.

**Comment by Nibba2018** [comment]
Hi @m-agour Thank you for the snippet. It seems to reproduces the same type of segfault :+1:

**Comment by Garyfallidis** [comment]
@m-agour thank you for reporting this. No issues on my Windows machine. Here are my settings.

'''
In [1]: import fury

In [2]: fury.get_info()
Out[2]:
{'fury_version': '0.8.0.post773+g223a6a2e',
 'pkg_path': 'c:\\users\\elef\\devel\\fury\\fury',
 'commit_hash': '223a6a2e2602904a218550bd3ad1547da0e53843',
 'sys_version': '3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]',
 'sys_executable': 'C:\\Users\\elef\\Anaconda3\\python.exe',
 'sys_platform': 'win32',
 'numpy_version': '1.20.3',
 'scipy_version': '1.7.1',
 'vtk_version': '9.1.0',
 'matplotlib_version': '3.4.3',
 'dipy_version': '1.6.0dev0'}
'''

Can you please report the same as above for your system?

**Comment by m-agour** [comment]
Hello @Garyfallidis,
This issue only occurs in Ubuntu (maybe other Linux distros). I just noticed that I didn't mention that in the issue title, so I will modify it.
Running the UI tests on my windows machine passes as well. 
I will log into my Ubuntu machine and post the report of the environment in which these tests are failing.
Report of my windows machine.
```
{'fury_version': '0.post3575+g38e9c1f',
 'pkg_path': 'A:\\contribution\\fury\\fury',
 'commit_hash': '38e9c1f0f84548619972d14ae33e7a2b4d9eda0e',
 'sys_version': '3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]',
 'sys_executable': 'C:\\Users\\msi\\AppData\\Local\\Programs\\Python\\Python310\\python.exe',
 'sys_platform': 'win32',
 'numpy_version': '1.23.1',
 'scipy_version': '1.8.1',
 'vtk_version': '9.2.0',
 'matplotlib_version': '3.5.2'}
```

**Comment by m-agour** [comment]
@Garyfallidis Using the environment below I get a segmentation fault running the UI tests, no matter which python version I'm using.

```
{'fury_version': '0.8.0.post744+gbca7b33c', 
'pkg_path': '/home/demon/contibution/fury/fury', 
'commit_hash': 'bca7b33c768fb6e38e791947de2c6c29ff99b87c', 
'sys_version': '3.8.10 (default, Jun 22 2022, 20:18:18) \n[GCC 9.4.0]', 
'sys_executable': '/home/demon/contibution/fury/venv/bin/python', 
'sys_platform': 'linux', 
'numpy_version': '1.22.4', 
'scipy_version': '1.8.1',
'vtk_version': '9.1.0', 
'matplotlib_version': '3.5.2'}
```

**Comment by skoudoro** [comment]
Vtk 9.2.0 ? Python 3.10 ? I didn't receive the release notice. When this happens ???!!!

**Comment by m-agour** [comment]
@skoudoro I got it when I was testing different versions of python for vtk's `timer_callback` accuracy. This was a month ago or so. I installed it from here https://vtk.org/download/. And it's been working fine!

**Comment by skoudoro** [comment]
> This was a month ago or so. I installed it from here https://vtk.org/download/. And it's been working fine!

Ah ok, this is a release candidate (rc1) makes sense now, no official 9.2.0 release yet.
