### ISSUE TITLE
Theme issues when docs compiled with latest sphinx-theme version

### ISSUE THREAD

**Issue by sreekarchigurupati** [fury-gl/fury#618]
## Description
pydata-sphinx-theme made backward incompatible changes in 0.9.0. The docs compiled with this version result in an auto dark mode which disrupts the theme. This is also inconsistent with the home page theming.

## Example generated doc
![Dark themes documentation](https://user-images.githubusercontent.com/13794515/177014835-b188ac95-7a77-4c0f-a1b4-32afe9b60569.png)

## Way to reproduce
Can be reproduced by running make on the docs using pydata-sphinx-theme:0.9.0

## Possible solution
- Freeze the theme version in CI build until code changes are made

**Comment by skoudoro** [comment]
It can be fixed by setting up `html_context` in `conf.py`

more information on this link: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html?highlight=dark%20mode#configure-default-mode

closing for now.
