### ISSUE TITLE
Textures are inverted in the tutorials

### ISSUE THREAD

**Issue by ganimtron-10** [fury-gl/fury#642]
## Description
As we can see below the Earth's texture (maybe other textures too) in the tutorials are inverted. This creates a miss-match in the coordinate points and the locations on the textures.

### `viz_earth_animation.py`
![python_VtzcD0M0bP](https://user-images.githubusercontent.com/64432063/180825427-e99785c3-1f8d-4da8-b83c-fd0c4d4584d3.png)
![python_xB5aQjs75B](https://user-images.githubusercontent.com/64432063/180825457-22dd1a36-ba76-4067-b147-e69e24dd1265.jpg)

### `viz_earth_coordinates.py`
![python_2fAhWL3oOl](https://user-images.githubusercontent.com/64432063/180825719-414cc587-241f-4b15-8adb-0eee15181cfd.jpg)
![python_yup9qDGL6E](https://user-images.githubusercontent.com/64432063/180825728-8a6626db-e86a-4dd4-90e0-19ed9515693d.jpg)

### `viz_solar_system.py`
![python_saXpWmg26f](https://user-images.githubusercontent.com/64432063/180825863-b88d3d94-e058-4b9b-ac00-2f3d608d0f46.png)

## Way to reproduce

Execute any of the following tutorials: `viz_solar_system.py`, `viz_earth_coordinates.py`, `viz_earth_animation`.

## System Specs
```
{'fury_version': '0.8.0.post845+g6c306bd6', 'pkg_path': 'd:\\furyworkspace\\fury\\fury', 'commit_hash': '6c306bd6dc4e7634a1998d2e2edc5120d939362e', 'sys_version': '3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]', 'sys_executable': 'D:\\FuryWorkspace\\fury-env\\Scripts\\python.exe', 'sys_platform': 'win32', 'numpy_version': '1.22.4', 'scipy_version': '1.8.1', 'vtk_version': '9.1.0', 'matplotlib_version': '3.5.2', 'dipy_version': '1.5.0'}
```

**Comment by skoudoro** [comment]
Good catch, thanks @ganimtron-10
