### ISSUE TITLE
viz_ui.py example needs expansion

### ISSUE THREAD

**Issue by Garyfallidis** [fury-gl/fury#71]
Currently the many UI components are hidden under one list box which makes it hard to figure out until you actually run the example and interact with it. We need to expand this tutorial to show all major interfaces with multiple figures and also show the File dialogue and load/save options.

**Comment by Saransh0905** [comment]
@Garyfallidis Can you tell what is File dialogue and load/save options in this context?

**Comment by skoudoro** [comment]
Hi @Saransh0905,

The goal of this issue is to split `viz_ui.py` tutorial into many tutorials.  Explicit better than implicit and this current tutorial hides too many functionalities currently.

So if you want to fix this issue, you need to create many UI tutorials

**Comment by skoudoro** [comment]
Fixed by #153. Closing
