### ISSUE TITLE
Earth coordinates tutorial example upsidedown

### ISSUE THREAD

**Issue by filipinascimento** [fury-gl/fury#714]
## Description
The example `fury/docs/tutorials/01_introductory/viz_earth_coordinates.py` is not working properly.

The world is upside down and the coordinates does not match the real locations. (Can't figure out what changed to make this happen, it works fine in  older versions.
<img width="562" alt="image" src="https://user-images.githubusercontent.com/600989/206652681-0f01fc49-2b3e-4849-9bb9-0d5703912065.png">

## Way to reproduce
Just run python `fury/docs/tutorials/01_introductory/viz_earth_coordinates.py`

## Version information

```
{
  'fury_version': '0.8.0',
  'pkg_path': '/Users/filsilva/miniforge3/envs/furyearth/lib/python3.9/site-packages/fury',
   'commit_hash': 'b937ff3418e7c64b0fa89921a54c083ff78dc055',
  'sys_version': '3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:48:25) \n[Clang 14.0.6 ]',
  'sys_executable': '/Users/filsilva/miniforge3/envs/furyearth/bin/python',
  'sys_platform': 'darwin',
  'numpy_version': '1.23.5',
  'scipy_version': '1.9.3',
  'vtk_version': '9.2.2',
  'matplotlib_version': '3.6.2'
}
```

- [x] Code example
- [x] Relevant images (if any)
- [x] Operating system and versions (run `python -c "from fury import get_info; print(get_info())"`)

**Comment by ganimtron-10** [comment]
Hello @filipinascimento,
I am closing this issue as the same issue is already created at #642 .
