### ISSUE TITLE
Missing fury.animation

### ISSUE THREAD

**Issue by jiayiliu-pku** [fury-gl/fury#743]
## Description
ModuleNotFoundError: No module named 'fury.animation'

I noticed that the animation folder is missing in the maint/v0.8.0 (the latest released version) branches.
I used conda to install fury: conda install -c conda-forge fury

## Way to reproduce
<img width="663" alt="48567120ab54d1fccf97b026bb21a60" src="https://user-images.githubusercontent.com/52529439/220368834-ccf80138-1763-4600-8811-7f88184e1c38.png">

**Comment by jiayiliu-pku** [comment]
I used conda to install fury.
conda install -c conda-forge fury

**Comment by skoudoro** [comment]
Hi @jiayiliu-pku,

Fury animation is not on DIPY release 0.8.0. it will be on the future release 0.9.0.

if you want to test this, please, use the main branch of the project and not pypi or conda

**Comment by jiayiliu-pku** [comment]
I got one another problem here.
I tried to test Fury animation. I download the main branch of the project and follow the installation step (via source). I successfully installed the requirement packages (pip install -r requirements/default.txt) However, I met another problem at **_pip install ._**. Could you help me with it? Thank you very much.
<img width="508" alt="82f5912b492402f8e8fc426be91e4e0" src="https://user-images.githubusercontent.com/52529439/222448897-a3e96360-bbcd-445c-8356-fef861ab4b1a.png">

**Comment by jiayiliu-pku** [comment]
Oh, I just downloaded the code from website instead use git clone.
I changed to use git clone and install fury successfully! Thank you!
