### ISSUE TITLE
Improve Checkbox initialisation

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#75]
## Description

Currently, it is quite hard to initialize checkbox on a specific state. By default, they are unchecked, but we want them already checked sometimes.

**Comment by Saransh0905** [comment]
@skoudoro What could be done to solve this?
Thanks

**Comment by ChenCheng0630** [comment]
@skoudoro 
Hi, I made some changes to allow users to pre-select checkboxes. 
Pls have a look when you have time :)

**Comment by skoudoro** [comment]
Nice @ChenCheng0630!  You can look at my first review but more coming
