### ISSUE TITLE
Improve Checkbox options access

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#76]
## Description

Currently, it is quite hard to get access to a specific options since it is a list. 2 strategies to make it simpler:
1. transform `options` attribute (from list to dict)
2. create a method on `CheckBoxUI` to get access to a specific option

**Comment by devmodi154** [comment]
Hey @skoudoro ! Can I work this issue?

**Comment by skoudoro** [comment]
yes, you can @devmodi154

**Comment by devmodi154** [comment]
#217

**Comment by devmodi154** [comment]
#217

**Comment by devmodi154** [comment]
> yes, you can @devmodi154

#217
