### ISSUE TITLE
contour_from_label

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#77]
## Description

like `contour_from_roi`, add the possibility to create the contours of a labeled array.

**Comment by subhashsuman01** [comment]
Hi,
I would like to work on this issue. Could anyone help me get started?

**Comment by skoudoro** [comment]
Hi @subhashsuman01 ,

Did you try `contour_from_roi` function and do you understand how it works? 

- If No,  I recommend you to start looking at the Tutorial and Examples on FURY website, look at [the contributing page](http://fury.gl/latest/contributing_link.html) and how VTK works.

- If Yes, you should be able to generate surface from a label array.

Hope it helps

**Comment by subhashsuman01** [comment]
Hi @skoudoro ,
I tried out the contour_from_roi function but I don't know how to get 3D numpy array of data points from a labeled array.

**Comment by grestonian** [comment]
Hi @skoudoro, I would like to work on this issue and go through the code and documentation about contour_from_roi function and will get back to you if I face any doubts. Is there any IRC where we can connect?

**Comment by Nibba2018** [comment]
hello @skoudoro , what exactly do you mean by a labeled array? can you give an example?

**Comment by skoudoro** [comment]
I think the tutorial below explains well what is a label array:

https://www.mathworks.com/help/images/label-and-measure-objects-in-a-binary-image.html

**Comment by Nibba2018** [comment]
@skoudoro Thank you the information. Could you provide me an example so that I can test my implementation?

**Comment by skoudoro** [comment]
fixed by #210, closing
