### ISSUE TITLE
TabUI collapsing/expanding improvements

### ISSUE THREAD

**Issue by guaje** [fury-gl/fury#776]
**Is your feature request related to a problem? Please describe.**

As shown in the following image, the TabUI starts in collapsed mode.

![tabui_issue_1](https://user-images.githubusercontent.com/9929496/229543675-7cec0c13-c21e-4ca5-aff7-14cf1852eed3.png)

**Describe the solution you'd like**

-  It would be helpful and more intuitive if the default behavior of this UI component would be the opposite yet still provide a parameter to initialize it collapsed for some applications.
- Additionally, it would be great to have the option to collapse/expand by double-clicking on any tab or single clicking on the active tab.

**Comment by alok1929** [comment]
Hey, I would love to work on this, could you guide me through it?

Thanks in advance.

**Comment by guaje** [comment]
Sure, create a PR in which you add a param to initialize the TabUI in expanded mode (`init_expanded=True`), implement the corresponding behavior, and of course, implement the opposite behavior. Then go to the related test file and add a test case that test your new functionality.
