### ISSUE TITLE
Tabs bar positioning in TabUI

### ISSUE THREAD

**Issue by guaje** [fury-gl/fury#780]
**Describe the solution you'd like**

The default behavior of tab-like UI components usually places them right above the content, e.g., web browser tabs. However, it would be helpful if, during the creation of a TabUI element, the user could specify where (top, bottom, left, or right) the tab bar should be placed.

![tab_layout](https://user-images.githubusercontent.com/9929496/231277565-dd240be4-3ed4-4f49-b4c3-38c935c9a766.png)

**Comment by rahulnandg** [comment]
hey, am interested in working on this one, I have proficiency in react html CSS and javascript.

**Comment by guaje** [comment]
> hey, am interested in working on this one, I have proficiency in react html CSS and javascript.

Great @rahulnandg! Looking forward to seeing your PR.

**Comment by nikhil478** [comment]
Hello @guaje, would you kindly share the code you used to create this

**Comment by nikhil478** [comment]
@guaje I am currently reviewing the demo and codebase, and it seems that Panel2D was used to create it. Panel2D has a position parameter and an align parameter that currently has two options: left and right. Do you want to have  four options (left, right, up, and down), or is there something else I may have missed? Could you please clarify?

**Comment by nikhil478** [comment]
> @guaje I am currently reviewing the demo and codebase, and it seems that Panel2D was used to create it. Panel2D has a position parameter and an align parameter that currently has two options: left and right. Do you want to have four options (left, right, up, and down), or is there something else I may have missed? Could you please clarify?

I would greatly appreciate any guidance and your feedback on this.

**Comment by IshanKamboj** [comment]
Hello @guaje , I would like to work on this issue. My proposed solution will be to make changes in the TabUI class and adding a new parameter for tab bar positioning and then making further changes in the positioning of the tabs and content according to the tab bar position specified. I would like you to please assign me this issue.

Thank you

**Comment by IshanKamboj** [comment]
> Hello @guaje , I would like to work on this issue. My proposed solution will be to make changes in the TabUI class and adding a new parameter for tab bar positioning and then making further changes in the positioning of the tabs and content according to the tab bar position specified. I would like you to please assign me this issue.
> 
> Thank you

Also does this issue require that we should be able to place the Tabs Bar at sides like left or right? .... If so then how should it actually look like, does it need to have text in vertical direction rather than horizontal? ... Please it would be very helpful if you can clarify this.
Thank you

**Comment by guaje** [comment]
> Hello @guaje , I would like to work on this issue. My proposed solution will be to make changes in the TabUI class and adding a new parameter for tab bar positioning and then making further changes in the positioning of the tabs and content according to the tab bar position specified. I would like you to please assign me this issue.
> 
> Thank you

Great! Looking forward to seeing your PR.

> Also does this issue require that we should be able to place the Tabs Bar at sides like left or right? .... If so then how should it actually look like, does it need to have text in vertical direction rather than horizontal? ... Please it would be very helpful if you can clarify this. Thank you

I suggest you start with a top/bottom PR, and then you can create a second PR for left/right.

**Comment by IshanKamboj** [comment]
> > Hello @guaje , I would like to work on this issue. My proposed solution will be to make changes in the TabUI class and adding a new parameter for tab bar positioning and then making further changes in the positioning of the tabs and content according to the tab bar position specified. I would like you to please assign me this issue.
> > Thank you
> 
> Great! Looking forward to seeing your PR.
> 
> > Also does this issue require that we should be able to place the Tabs Bar at sides like left or right? .... If so then how should it actually look like, does it need to have text in vertical direction rather than horizontal? ... Please it would be very helpful if you can clarify this. Thank you
> 
> I suggest you start with a top/bottom PR, and then you can create a second PR for left/right.

All right, will make the first PR soon
Thank you

**Comment by Preetam-Das26** [comment]
Is this issue resolved?

**Comment by MukulGupta005** [comment]
Hi @guaje I would like to work on this issue

**Comment by skoudoro** [comment]
Hi @MukulGupta005,

there is already a pull request by @IshanKamboj  that we need to review
