### ISSUE TITLE
Segmentation Fault while plotting (diffusion tractography) images on a non-interactive remote cluster

### ISSUE THREAD

**Issue by man-shu** [fury-gl/fury#787]
## Description
I wanted to plot diffusion tractography images as in [viz_bundles.py](https://fury.gl/latest/auto_examples/04_demos/viz_bundles.html#sphx-glr-auto-examples-04-demos-viz-bundles-py) example, but I want to do that a non-interactive remote high-performance computing cluster (because the tractography files are huge ~5Gb). But when I do that, or even if I simply run `python viz_bundles.py` I get a segmentation fault error. I suspect this is because vtk tries to render a GUI window in the background, which can't be done because the resources aren't available on the non-interactive cluster.

So I just wanna know if this is at all possible with dipy/fury yet? If so, please let me know how.

## Way to reproduce
I ran viz_bundles.py on my local machine, and it works fine there but fails on the remote cluster.
I have attached the gdb traceback for the run on remote cluster here: [traceback.txt](https://github.com/fury-gl/fury/files/11564772/traceback.txt)

{'fury_version': '0.9.0', 'pkg_path': '/scratch/haggarwa/qmri_condapy/lib/python3.9/site-packages/fury', 'commit_hash': '<not found>', 'sys_version': '3.9.5 (default, Jun  4 2021, 12:28:51) \n[GCC 7.5.0]', 'sys_executable': '/scratch/haggarwa/qmri_condapy/bin/python', 'sys_platform': 'linux', 'numpy_version': '1.22.1', 'scipy_version': '1.9.1', 'vtk_version': '9.2.6', 'matplotlib_version': '3.5.0', 'dipy_version': '1.7.0'}

- [x] Code example
- [x] Relevant images (if any)
- [x] Operating system and versions (run `python -c "from fury import get_info; print(get_info())"`)

**Comment by skoudoro** [comment]
Hi @man-shu,

Are you using the `offscreen=True` option ?

Which line is crashing ? 

> o I just wanna know if this is at all possible with dipy/fury yet?

yes, it is

ps: sorry for the late reply
