### ISSUE TITLE
add link to fury example gallery in sphinx-gallery readme

### ISSUE THREAD

**Issue by agramfort** [fury-gl/fury#79]
it's not a but a suggestion to add link to http://fury.gl/latest/auto_examples/index.html
in sphinx-gallery readme. See for example

https://github.com/sphinx-gallery/sphinx-gallery/pull/504/files

**Comment by skoudoro** [comment]
Sounds like a good suggestion, thank you @agramfort! Will do as soon as I have access to a computer

**Comment by skoudoro** [comment]
Done in https://github.com/sphinx-gallery/sphinx-gallery/pull/515. closing
