### ISSUE TITLE
Add superquadric function in actor.py

### ISSUE THREAD

**Issue by Garyfallidis** [fury-gl/fury#81]
Adding a supequadric function should be very similar to the cone function. See here
https://github.com/fury-gl/fury/blob/master/fury/actor.py#L1453

All needs to change is this line
https://github.com/fury-gl/fury/blob/master/fury/actor.py#L1510

To use this class and of course update the parameters
https://vtk.org/doc/nightly/html/classvtkSuperquadricSource.html
Alternatively you can derive the parameters from the superquadric equation directly.

**Comment by skoudoro** [comment]
New feature added by #131, closing
