### ISSUE TITLE
Save from active window? 

### ISSUE THREAD

**Issue by arokem** [fury-gl/fury#85]
It used to be possible to save from an active window by hitting the 's' button. Was that functionality deprecated/altered? How do I now save from an active window?

**Comment by Garyfallidis** [comment]
Yes, it was removed for generality as some apps could be using s for something else.
Simply add a button and a callback on the button that will call window.snapshot or window.record.

**Comment by arokem** [comment]
Is there an example of that somewhere? Or even just a simple example of using Button2D? I don't understand what the `icon_fnames` should look like.

**Comment by Garyfallidis** [comment]
Any image (png) can become a button. 
https://github.com/fury-gl/fury/blob/master/docs/tutorials/viz_ui.py#L77

**Comment by Garyfallidis** [comment]
There should be a save icon in the collections of icons we provide.

**Comment by arokem** [comment]
Oh perfect - that example is exactly what I needed!

**Comment by Garyfallidis** [comment]
;)
