### ISSUE TITLE
Missing files for sprite test

### ISSUE THREAD

**Issue by skoudoro** [fury-gl/fury#864]
Hi @antrikshmisri,

I hope you are doing well.

we are encountering an issue because it seems you remove a file from your repo: see the error below:

```
    def test_load_sprite_sheet():
        sprite_URL = (
            'https://raw.githubusercontent.com/'
            'antrikshmisri/DATA/master/fury/0yKFTBQ.png'
        )
    
        with InTemporaryDirectory() as tdir:
>           sprites = load_sprite_sheet(sprite_URL, 5, 5)

    def http_error_default(self, req, fp, code, msg, hdrs):
>       raise HTTPError(req.full_url, code, msg, hdrs, fp)
E       urllib.error.HTTPError: HTTP Error 404: Not Found

```
from https://github.com/fury-gl/fury/actions/runs/7104234151/job/19338742838#step:12:543

Can you please let us know which file it is and we will move it to https://github.com/fury-gl/fury-data and update the url.

Thank you for your feedback

**Comment by antrikshmisri** [comment]
Hey @skoudoro, thank you for pointing this out. I changed the visibility of the repository to private a while back. Sorry for not notifying you about it. I have attached the file to this comment. Let me know if it works.
![0yKFTBQ](https://github.com/fury-gl/fury/assets/54466356/d1f6c5f5-4207-4262-b02b-ceb7c29580dd)
