### ISSUE TITLE
Make PyGLTFLib an optional dependency

### ISSUE THREAD

**Issue by guaje** [fury-gl/fury#873]
**Is your feature request related to a problem? Please describe.**
PyGLTFLib usage in the codebase is lower than some optional dependencies, such as DIPY.

**Describe the solution you'd like**
Make PyGLTFLib an optional dependency.

**Comment by noobyco** [comment]
moving PyGLTFLib from ```requirements/default``` to ```requirements/optional``` shuold do the thing. I'm on it.

**Comment by guaje** [comment]
> moving PyGLTFLib from `requirements/default` to `requirements/optional` shuold do the thing. I'm on it.

You also need to look for its usage in the codebase and ensure it doesn't throw errors when pyGLTFlib is not installed in the user's environment.

**Comment by noobyco** [comment]
>  moving PyGLTFLib from `requirements/default` to `requirements/optional` shuold do the thing. I'm on it.
> 
> You also need to look for its usage in the codebase and ensure it doesn't throw errors when pyGLTFlib is not installed in the user's environment.

Yeah sure!

**Comment by robinroy03** [comment]
@noobyco, you still working on this issue? I'll be happy to help.

**Comment by noobyco** [comment]
> @noobyco, you still working on this issue? I'll be happy to help.

I have created a PR https://github.com/fury-gl/fury/pull/875 but I do need to check one thing mentioned below. Yup, we can work together if you want just hit me on Twitter https://twitter.com/noobyco :)

`You also need to look for its usage in the codebase and ensure it doesn't throw errors when pyGLTFlib is not installed in the user's environment.`

**Comment by janhavi-naik14** [comment]
1)Update dependency management: Modify requirements.txt, create requirements-optional.txt, and update setup.py.
2)Modify the codebase: Use try...except for importing PyGLTFLib and conditionally handle its functionality.
3)Update documentation: Inform users about the optional dependency and how to install it.
4)Test the changes: Verify that the application works with and without the optional dependency.

**Comment by skoudoro** [comment]
we keep it as a mandatory dependencies for the 0.x series.

We will remove this dependency in the 1.xxx series (fury v2)

thanks all for your feedback
