### ISSUE TITLE
Warning on the website

### ISSUE THREAD

**Issue by raycite** [fury-gl/fury#936]
## Description

![Screenshot from 2024-09-28 12-42-47](https://github.com/user-attachments/assets/8371cbcc-481b-4892-a74a-5f8b1f729bd1)

## Way to reproduce
https://fury.gl/latest/auto_examples/01_introductory/viz_arrow.html#sphx-glr-auto-examples-01-introductory-viz-arrow-py

**Comment by wasserth** [comment]
Is there any solution to this? These warnings are quite annoying and I did not manage to find out how to call the functions differently to avoid the warnings. The tutorial / examples apparently have also not been updated to the new function definitions.

**Comment by skoudoro** [comment]
Hi @wasserth,

it seems we missed some update on our tutorials. I will. update that this Friday.

Now we follow pep 3102 : https://peps.python.org/pep-3102/

You just need to be explicit with all function arguments to silent the warnings. 

in this specific case:
`fury.window.record(scene, out_path="viz_arrow.png", size=(600, 600))` should be
`fury.window.record(scene=scene, out_path="viz_arrow.png", size=(600, 600))`. 

I hope it helps to update your code and avoid those warnings. 
Note that those warnings will become an error after several realeases.

**Comment by skoudoro** [comment]
fixed by #939, closing
